- servant.cabal
- src/Servant/API/ContentTypes.hs
- test/Servant/API/ContentTypesSpec.hs
This depends on https://github.com/haskell-servant/servant/pull/9. It support for url encoded request bodys. To use a custom type, There is these typeclasses:
```.haskell
class ToFormUrlEncoded a where
toFormUrlEncoded :: a -> [(TextL.Text, TextL.Text)]
class FromFormUrlEncoded a where
fromFormUrlEncoded :: [(TextL.Text, TextL.Text)] -> Either String a
```
> Add support for application/x-www-form-urlencoded

- .travis.yml
- TODO.md
- servant.cabal
- src/Servant/API.hs
- src/Servant/API/Alternative.hs
- src/Servant/API/Capture.hs
- src/Servant/API/ContentTypes.hs
- src/Servant/API/Delete.hs
- src/Servant/API/Get.hs
- src/Servant/API/Header.hs
- src/Servant/API/MatrixParam.hs
- src/Servant/API/Patch.hs
- src/Servant/API/Post.hs
- src/Servant/API/Put.hs
- src/Servant/API/QueryParam.hs
- src/Servant/API/ReqBody.hs
- src/Servant/API/Sub.hs
- src/Servant/Common/Text.hs
- test-docs.sh
- test/Doctests.hs
- test/Servant/Common/TextSpec.hs
- Integrated doctests into cabal
- Doctest more of the documentation
- Remove the (:>) constructor
- Give kind signatures to Symbols
- Make all constructors typeable
- Use stylish-haskell for consistency of styling
- Cleanup documentation
- Remove old TODO.md
> Cleanup, including:

- CHANGELOG.md
- src/Servant/API.hs
- src/Servant/API/ContentTypes.hs
Hello folks,
While thinking about the more formal aspects of servant with @jkarni, I mentionned that I was uncomfortable with the fact that we couldn't state some kinds of "laws" for *interpretations* of an API type, like:
``` haskell
Server (a :<|> b) = Server a :<|> Server b -- this one holds
Server (a :> (b :<|> c)) = Server (a :> b) :<|> Server (a :> c) -- this one doesn't!
```
Julian seemed just as comfortable with this as I am and after giving it some thought, we found a solution:
``` haskell
-- | Turn an API type into its canonical form.
--
-- The canonical form is defined and will basically turn:
--
-- > "hello" :> (Get Hello :<|> ReqBody Hello :> Put Hello)
--
-- into
--
-- > ("hello" :> Get Hello) :<|> ("hello" :> ReqBody Hello :> Put Hello)
--
-- i.e distributing all …
```
> Canonical types

- src/Servant/Common/Text.hs
- src/Servant/Utils/Links.hs
- test/Servant/Common/TextSpec.hs
- test/Servant/Utils/LinksSpec.hs
I got distracted by broken tests and fixed #17 whilst correcting a breakage when moving to the new definition of ReqBody with content types. This fixes both.
Need review on:
* Importing GHC.Float, is this OK?
* Conversion is now going via Double for float, as the rational function does some weird round offs, is this OK?
* Are 15 significant bits for Double and 7 for Float a reasonable amount of precision to expect?
> Fix a HasLink instance, also fix float text handling/tests.

- .travis.yml
- CHANGELOG.md
- servant.cabal
- src/Servant/API.hs
- src/Servant/API/ContentTypes.hs
- src/Servant/API/Header.hs
- src/Servant/API/ResponseHeaders.hs
- test/Servant/API/ContentTypesSpec.hs
- test/Servant/API/ResponseHeadersSpec.hs
Provides an easy way to add headers to responses:
```
type MyEndpoint = Get '[JSON] (Headers [Header "Location" Link] Int)
myEndpoint :: Server MyEndpoint
myEndpoint = return $ addHeader <somelink> 5
```
> Add response headers.

- scripts/shell.nix
- servant-examples/LICENSE
- servant-examples/Setup.hs
- servant-examples/auth-combinator/auth-combinator.hs
- servant-examples/hackage/hackage.hs
- servant-examples/servant-examples.cabal
- servant-examples/wai-middleware/wai-middleware.hs
- sources.txt
- `hackage/hackage.hs` shows how to quickly derive client functions for a couple of JSON endpoints in hackage's API;
- `wai-middleware/wai-middleware.hs` shows how to apply a WAI middleware, in particular the one that logs every request to stdout.
- `auth-combinator/auth-combinator.hs` is a small adaptation of the code presented at the Haskell SG meetup by Soenke & Julian.
I also added `servant-examples` to the sources & the nix file.
> Add a servant-examples dir with 3 "classical" examples (and more to come?)

- servant-docs/src/Servant/Docs.hs
- servant-docs/src/Servant/Docs/Internal.hs
We simply forgot to export them.
> add missing exports (lenses) to servant-docs's Servant.Docs module

- servant-server/servant-server.cabal
- servant-server/test/Doctests.hs
- servant/servant.cabal
- servant/test/Doctests.hs
Not the most elegant code, but I think this is the best fix.
> fix doctests for cabal-install-1.18

- servant-server/test/Doctests.hs
- servant/test/Doctests.hs
They seem to encounter multiple sandboxes sometimes, we now provide a more
helpful error if that happens. Didn't look into why this happens.
> servant, servant-server: handle corner case in doctests

- servant-server/servant-server.cabal
- servant-server/src/Servant/Utils/StaticFiles.hs
system-filepath was just deprecated http://www.yesodweb.com/blog/2015/05/deprecating-system-filepath
This also fixes #81
> Add support for wai-app-static-3.1.0

- servant/src/Servant/API/ContentTypes.hs
- servant/test/Servant/API/ContentTypesSpec.hs
This includes some de-duplication in the test suite, got carried away.
Important changes are ```eitherDecodeLenient``` and test suites surrounding that.
> servant: allow whitespace after parsing JSON

- servant/src/Servant/Utils/Links.hs
This is a fix for #92.
The change itself is straight forward. To test for regression, it is checked (with `-fdefer-type-errors`) that `IsElem` doesn't yield an empty `Constraint`.
> More strict matching for Capture (safeLink)

- servant-docs/servant-docs.cabal
- servant-docs/src/Servant/Docs/Internal.hs
- servant-docs/test/Servant/DocsSpec.hs
Hi,
thanks for this nice library :)
I noticed that the enpoints vanished from the documentation when adding extra info via docsWith. This pull-request fixes that.
Best,
Philipp
> servant-docs: Fix docsWith.

- servant/test/Servant/API/ContentTypesSpec.hs
If the version of aeson used is below 0.9 the current ordering
results in an empty do block.
> Fix ordering of CPP directive for aeson test

- servant-client/src/Servant/Common/Req.hs
- servant-client/test/Servant/ClientSpec.hs
This simplifies the error type. This allows for `http-client` to be swapped out (#51).
> Don't export HttpException

- scripts/bump-versions.sh
- scripts/lib/common.sh
This also makes it behave when called from from any directory.
> Make bump-versions.sh work

- servant-docs/src/Servant/Docs/Internal.hs
That way it's easier to document that the endpoints on the LHS "fall
through" to the RHS.
> Make HasDocs instance for :<|> overlappable.

- servant-js/src/Servant/JS.hs
Previous definition only let you define one API containing all the API
This way, you can divide it into small pieces
```haskell
type PartAPI = ...
type AppAPI = ... :<|> PartAPI
```
> Fix GenerateList to let the API be nested

- servant-client/CHANGELOG.md
- servant-client/src/Servant/Common/BaseUrl.hs
- servant-client/src/Servant/Common/Req.hs
- servant-client/test/Servant/ClientSpec.hs
- servant-examples/hackage/hackage.hs
- servant-examples/tutorial/T8.hs
This pull request fixes #203. It adds another field, `path`, to the `BaseUrl` value.
> Fix #203; add path to BaseUrl

- .travis.yml
- servant-mock/servant-mock.cabal
- stack-ghc-7.8.4.yaml
- stack.yaml
This PR switches our travis builds to stack. Build times of this branch are about 4 minutes.
The one caveat (that has been discussed before) of this switch is that we don't test for hackage breakage through travis anymore. I talked about this with @jkarni and we thought it would be best to set up a separate CI (not through travis) for this. He's working on that.
cc: @alpmestan
> make travis builds use stack

- servant-docs/src/Servant/Docs/Internal.hs
- servant-js/src/Servant/JS/Internal.hs
`List` is a pattern synonym added in `lens-4.13`. (It doesn't show up in the documentation on hackage currently -- I assume haddock doesn't support pattern synonyms?)
> fix for lens-4.13

- servant-docs/src/Servant/Docs/Internal.hs
- servant-docs/test/Servant/DocsSpec.hs
On request by @jkarni.
Not sure about the cross product for the individual tuple components.  Are there better ways?  I guess you can always overload the instance if output gets too big.
I couldn't come up with interesting tests.  Can you?
Would you like support for 12-tuples?  What's the right number to stop at?
Lists?  Maybe?  Either?  What else?  I think it's most interesting for tuples, but I am happy to add more.
> ToSample instances for tuples.

- servant-foreign/CHANGELOG.md
- servant-foreign/LICENSE
- servant-foreign/README.md
- servant-foreign/Setup.hs
- servant-foreign/servant-foreign.cabal
- servant-foreign/src/Servant/Foreign.hs
- servant-js/servant-js.cabal
- servant-js/src/Servant/JS.hs
- servant-js/src/Servant/JS/Angular.hs
- servant-js/src/Servant/JS/Axios.hs
- servant-js/src/Servant/JS/Internal.hs
- servant-js/src/Servant/JS/JQuery.hs
- servant-js/src/Servant/JS/Vanilla.hs
- servant-js/test/Servant/JSSpec.hs
- servant-js/test/Servant/JSSpec/CustomHeaders.hs
- sources.txt
- stack-ghc-7.8.4.yaml
- stack.yaml
For the step one of this task i targeted only `servant-js`, so the current refactoring was pretty mechanical. What i wanted to achieve is:
* extract `Servant.JS.Internal` to make unification with other libraries(such as [lackey](https://hackage.haskell.org/package/lackey)) easier
* `HasJS` and `JS` got renamed to `HasForeign` and `Foreign`, but basically stayed the same
* `servant-js` should depend only on `servant-foreign`. There are currently an example which depends on `servant` though.
What do you think? How do you think we should proceed? If it's ok with you, we can have this by `0.5` release and push `servant-foreign` to hackage by that time. I'm not really familiar with servant release cycle, so please correct me if i'm wrong with my assumptions somewhere.
[<img …
> Common code generation types and helpers extracted to servant-foreign

- servant-client/src/Servant/Client.hs
When using the Plivo API to send a text message through SMS, the response has status code 202 "Accepted", which results in servant throwing an error because it does not recognize this as a valid success code. I added status code 202 to Servant.Client for Post responses to fix this problem.
> added status code 202 to servant-client POST responses

- .travis.yml
The `build` in the `.travis.yml` file is redundant. `stack test` is just
an alias for `stack build --test`.
Also in the old way of doing things,  `-Werror` is actually not set when
running tests. So it is ignored for  test files..
Now also test files need to have no warnings.
> Remove redundant build from .travis.yml file.

- servant-client/src/Servant/Common/BaseUrl.hs
- servant-client/test/Servant/ClientSpec.hs
- servant-client/test/Servant/Common/BaseUrlSpec.hs
- servant-client/test/Spec.hs
For some reason hspec-discover wasn't enabled for servant-client,
causing test cases to be skipped and fasely reporting servant-client as
test-passing whilst it was actually supposed to fail the tests.
For example, we redefined BaseUrl recently to have a path field, but the
tests don't reflect that yet but passed anyway. Because the test case
wasn't even discovered and run.
> Fix servant-client tests to properly use hspec-discover.

- servant-docs/src/Servant/Docs/Internal.hs
- servant-examples/auth-combinator/auth-combinator.hs
- servant-server/CHANGELOG.md
- servant-server/servant-server.cabal
- servant-server/src/Servant/Server.hs
- servant-server/src/Servant/Server/Internal.hs
- servant-server/src/Servant/Server/Internal/Router.hs
- servant-server/src/Servant/Server/Internal/RoutingApplication.hs
- servant-server/src/Servant/Server/Internal/ServantErr.hs
- servant-server/test/Servant/Server/ErrorSpec.hs
- servant-server/test/Servant/ServerSpec.hs
- servant/CHANGELOG.md
- servant/src/Servant/API/ContentTypes.hs
- servant/test/Servant/API/ContentTypesSpec.hs
Looking pretty bad:
```
servant-server-0.5: test (suite: doctests, args: -m "HTTP Errors")
Examples: 7  Tried: 7  Errors: 0  Failures: 0
servant-server-0.5: test (suite: spec, args: -m "HTTP Errors")
Servant.Server.Error
HTTP Errors
HTTP error order
has 404 as its highest priority error FAILED [1]
has 405 as its second highest priority error
has 415 as its third highest priority error
has 400 as its fourth highest priority error
has 406 as its fifth highest priority error FAILED [2]
returns handler errors as its lower priority errors
Handler search
should continue when URLs don't match FAILED [3]
should continue when methods don't match FAILED [4]
should not continue when Content-Types don't match
should not continue when body can't be deserialized FAILED [5]
should not continue when …
```
> Fix error priority and retries

- servant-js/src/Servant/JS.hs
Allow `defCommonGeneratorOptions` to be customized using record update syntax.
Without the re-export, we can't do things like:
```haskell
import qualified Servant.JS as SJS
myOptions =
SJS.defCommonGeneratorOptions
{ SJS.moduleName = "myModule"
, SJS.urlPrefix = "http://localhost"
}
```
> servant-js: export CommonGeneratorOptions constructors

- servant-foreign/servant-foreign.cabal
- servant-foreign/src/Servant/Foreign.hs
- servant-foreign/test/Servant/ForeignSpec.hs
- servant-foreign/test/Spec.hs
Previous behaviour was a bit shouty (and dashes aren't allowed in JS variable names):
```haskell
camelCase ["one", "two", "thirty-three"] -- => "oneTWOTHIRTY-THREE"
```
New behaviour:
```haskell
camelCase ["one", "two", "thirty-three"] -- => "oneTwoThirtythree"
```
> Fix camelCase

- servant-js/README.md
This PR fix a broken link at the [README.md](https://github.com/haskell-servant/servant/blob/master/servant-js/README.md) file.
> [servant-js] README-md - Fix broken link

- servant-foreign/servant-foreign.cabal
- servant-foreign/src/Servant/Foreign.hs
- servant-foreign/src/Servant/Foreign/Internal.hs
- servant-foreign/test/Servant/ForeignSpec.hs
- servant-js/servant-js.cabal
- servant-js/src/Servant/JS.hs
- servant-js/src/Servant/JS/Angular.hs
- servant-js/src/Servant/JS/Axios.hs
- servant-js/src/Servant/JS/Internal.hs
- servant-js/src/Servant/JS/JQuery.hs
- servant-js/src/Servant/JS/Vanilla.hs
- servant-js/test/Servant/JSSpec.hs
- servant-js/test/Servant/JSSpec/CustomHeaders.hs
I'm creating [C# backend](https://github.com/MaxOw/servant-sharp) to servant and need access to types. All this is basically a `HasForeignType` class and all the piping around it. Then when creating backend you just provide equivalent backend language types for all haskell types that you are interested in, by providing instances to that class. Specifically in dynamic languages you just need to provide empty, catch all, instance.
> Type information in servant-foreign.

- servant-docs/servant-docs.cabal
- servant-docs/src/Servant/Docs.hs
- servant-docs/src/Servant/Docs/Internal.hs
- servant-docs/src/Servant/Docs/Internal/Pretty.hs
Here's one solution to #127. 
Adds one function `pretty :: Proxy api -> Proxy (Pretty api)` to get pretty-printed JSON in generated documentation.
> Add 'pretty' to servant-docs

- servant-docs/src/Servant/Docs/Internal/Pretty.hs
Launching `nix-shell` with `./servant-examples/shell.nix` generated by `./scripts/generate-nix-files.sh` gives an error:
```
Building servant-docs-0.5...
Preprocessing library servant-docs-0.5...
[1 of 3] Compiling Servant.Docs.Internal.Pretty ( src/Servant/Docs/Internal/Pretty.hs, dist/build/Servant/Docs/Internal/Pretty.o )
src/Servant/Docs/Internal/Pretty.hs:17:1: Warning:
The import of ‘Servant.API.ContentTypes’ is redundant
except perhaps to import instances from ‘Servant.API.ContentTypes’
To import instances alone, use: import Servant.API.ContentTypes()
src/Servant/Docs/Internal/Pretty.hs:18:1: Warning:
The import of ‘Servant.Utils.Links’ is redundant
except perhaps to import instances from ‘Servant.Utils.Links’
To import instances alone, use: import Servant.Utils.Links()
<no …
```
> [servant-docs] Removed redundant imports.

- servant-cassava/src/Servant/CSV/Cassava.hs
This allows the same API type to be used for `serve` and `client`.
> MimeUnrender and MimeRender instances for Cassava

- servant-server/src/Servant/Server.hs
Or was there a good reason for this section being different than the others?
> server/docs: fix formatting inconsistency

- servant-foreign/src/Servant/Foreign.hs
- servant-foreign/src/Servant/Foreign/Internal.hs
- servant-foreign/test/Servant/ForeignSpec.hs
- servant-js/src/Servant/JS/Angular.hs
- servant-js/src/Servant/JS/Axios.hs
- servant-js/src/Servant/JS/Internal.hs
- servant-js/src/Servant/JS/JQuery.hs
- servant-js/src/Servant/JS/Vanilla.hs
I felt like i have to do this before addressing a few other issues with servant-foreign
Basically it's:
* non-messy imports
* got rid of most long lines (>80 chars)
* prisms for sum types and newtypes(we use lens anyway, so why not)
* consistent indentation
Also i made some changes to demonstrate my point from https://github.com/haskell-servant/servant/pull/345#issuecomment-182807730
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/haskell-servant/servant/372)
> Make servant-foreign code nicer

- servant-client/CHANGELOG.md
- servant-client/servant-client.cabal
- servant-client/src/Servant/Client.hs
- servant-client/src/Servant/Common/BasicAuth.hs
- servant-client/test/Servant/ClientSpec.hs
- servant-docs/CHANGELOG.md
- servant-docs/src/Servant/Docs/Internal.hs
- servant-examples/basic-auth/basic-auth.hs
- servant-examples/servant-examples.cabal
- servant-server/CHANGELOG.md
- servant-server/servant-server.cabal
- servant-server/src/Servant/Server.hs
- servant-server/src/Servant/Server/Internal.hs
- servant-server/src/Servant/Server/Internal/BasicAuth.hs
- servant-server/src/Servant/Server/Internal/RoutingApplication.hs
- servant-server/test/Servant/Server/ErrorSpec.hs
- servant-server/test/Servant/ServerSpec.hs
- servant/CHANGELOG.md
- servant/servant.cabal
- servant/src/Servant/API.hs
- servant/src/Servant/API/BasicAuth.hs
This pull-request takes the basic authentication code from https://github.com/haskell-servant/servant/pull/341 . It uses none of the generalized authentication framework, including the `AuthReturnType` type family used in the previous request. 
This should provide a very simple example of using `Config` in conjunction with a authentication pattern where the only user-defined type are server specific (e.g. `servant-client` only concerns itself with the concrete `BasicAuthData` datatype)
> Basic Authentication Support

- servant-foreign/servant-foreign.cabal
- servant-foreign/src/Servant/Foreign.hs
- servant-foreign/src/Servant/Foreign/Inflections.hs
- servant-foreign/src/Servant/Foreign/Internal.hs
- servant-foreign/test/Servant/ForeignSpec.hs
- servant-js/src/Servant/JS/Angular.hs
- servant-js/src/Servant/JS/Axios.hs
- servant-js/src/Servant/JS/Internal.hs
- servant-js/src/Servant/JS/JQuery.hs
- servant-js/src/Servant/JS/Vanilla.hs
- servant-js/test/Servant/JSSpec/CustomHeaders.hs
I've started working on https://github.com/dredozubov/servant-rust and it seems like `servant-foreign` is currently stringly-typed. This patch makes use of newtypes and some convenience lenses to make user's lives a bit happier. Also https://github.com/haskell-servant/servant/issues/377
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/haskell-servant/servant/378)
> Utilize newtypes in servant-foreign

- servant-foreign/servant-foreign.cabal
- servant-foreign/src/Servant/Foreign.hs
- servant-foreign/src/Servant/Foreign/Internal.hs
- servant-foreign/test/Servant/ForeignSpec.hs
- servant-js/src/Servant/JS.hs
- servant-js/src/Servant/JS/Angular.hs
- servant-js/src/Servant/JS/Axios.hs
- servant-js/src/Servant/JS/Internal.hs
- servant-js/src/Servant/JS/JQuery.hs
- servant-js/src/Servant/JS/Vanilla.hs
- servant-js/test/Servant/JSSpec.hs
- servant-js/test/Servant/JSSpec/CustomHeaders.hs
With these changes, we allow a user-specified type to represent the foreign type of Haskell types encountered in the API. This lets users map Integer, Date etc. to representations other than Text, and have those representations available in the returned list of Req.
For example, we might want to map a type which has an instance of Generic to both a foreign type name and a class declaration for that foreign type such that it can encode/decode itself to JSON. The previous limitation to a single Text output prevented this case.
This is all implemented by explicitly parameterising various types with the desired output type: for `NoTypes`, this is `()`. For typed languages, the implementor might want it to be a custom record type containing necessary "import" directives, the foreign type name, …
> servant-foreign: don't constrain ForeignType to Text

- doc/tutorial/index.rst
I've added a "note" to the tutorial page - it looks like this: https://i.imgur.com/4iNGWWs.png
> Add link to old tutorial (0.4)

- servant/servant.cabal
Since `servant` currently doesn't compile with `ghc-8`.
Changing this in `servant` should be enough, since every package in here depends on it.
CC: @phadej
> cabal: decrease upper bound for base to disallow ghc-8

- doc/tutorial/Client.lhs
- servant-client/CHANGELOG.md
- servant-client/src/Servant/Client.hs
- servant-client/src/Servant/Common/Req.hs
- servant-client/test/Servant/ClientSpec.hs
This PR removes the `BaseUrl` and `Manager` parameters from the `client` function, as discussed in #428. In turn, the type of all client functions changes from `ExceptT ServantError IO a` to `ReaderT BaseUrl (ReaderT Manager (ExceptT ServantError IO)`. For convenience, I have defined a type named `ClientM` as an alias for this.
> Manager in client

- servant-server/CHANGELOG.md
- servant-server/src/Servant/Server.hs
- servant-server/src/Servant/Server/Internal.hs
- servant-server/src/Servant/Server/Internal/Router.hs
- servant-server/src/Servant/Server/Internal/RoutingApplication.hs
- servant-server/test/Servant/Server/RouterSpec.hs
- servant-server/test/Servant/ServerSpec.hs
I wanted to understand my own router machinery better, and write about it and test it. Therefore, I have added code that can display how the generated router actually looks like.
Here is a small example:
```
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}
import Data.Text.IO as T
import Data.Proxy
import Servant.API
import Servant.Server
type End1 = Get '[JSON] ()
type End2 = Put '[JSON] ()
type API1 =
"a" :> "b" :> End1
:<|> "a" :> "c" :> Capture "n" Int :> "d" :> End1
type API2 =
"b" :> End1
:<|> "a" :> "d" :> End1
type API3 =
"a" :> "b" :> End2
:<|> "a" :> "c" :> Capture "n" Int :> "e" :> End2
type API = API1 :<|> API2 :<|> API3
main :: IO ()
main = T.putStr (layout (Proxy :: Proxy API))
```
This produces:
```
<root>
├─ a
│  ├─ b
│  │  ┆
│  │  ├─•
│  │  ┆
│  │  └─•
│  ├─ c
│ …
```
> Improvements of router merging, visualization and testing

- servant-mock/src/Servant/Mock.hs
The example in the haddock does not coincide with the example code in servant-mock/example/main.hs
> Fix code example in haddock  of servant-mock

- doc/tutorial/Authentication.lhs
- servant-docs/CHANGELOG.md
- servant-server/CHANGELOG.md
- servant-server/src/Servant.hs
- servant/CHANGELOG.md
> Re-export `throwError` from module `Servant`

- servant-server/CHANGELOG.md
- servant-server/src/Servant/Server.hs
- servant-server/src/Servant/Server/Experimental/Auth.hs
- servant-server/src/Servant/Server/Internal.hs
- servant-server/src/Servant/Server/Internal/BasicAuth.hs
- servant-server/src/Servant/Server/Internal/Router.hs
- servant-server/src/Servant/Server/Internal/RoutingApplication.hs
- servant-server/test/Servant/Server/RouterSpec.hs
- servant-server/test/Servant/Server/UsingContextSpec/TestCombinators.hs
- servant-server/test/Servant/ServerSpec.hs
Thanks to @fizruk for exposing a significant flaw in the former `Router` type.
This PR is based on top of #451, assuming that one will get merged, because it affects the same code and would otherwise cause lots of conflicts.
We've previously used functions in the `Router` type to provide information for subrouters. But this accesses the `Request`s too early, and breaks sharing of the router structure in general, causing the `Router` or large parts of the `Router` to be recomputed on every request.
We now do not use functions anymore, and properly compute all static parts of the router first, and gain access to the request only in `Delayed`.
This also turns the code used within `Delayed` into a proper monad now called `DelayedIO`, making some of the code using it a bit nicer.
> Fix router sharing

- servant-server/servant-server.cabal
- servant/src/Servant/API/ContentTypes.hs
This builds with the current state of the `ghc-8.0` branch.
I'm not entirely certain about the `ContentTypes` change. Someone more familiar with this code should have a closer look before merging.
> Compatibility with GHC 8.0

- servant-server/CHANGELOG.md
- servant-server/src/Servant/Server/Internal.hs
- servant-server/src/Servant/Server/Internal/RoutingApplication.hs
- servant-server/test/Servant/Server/ErrorSpec.hs
- servant-server/test/Servant/ServerSpec.hs
This is a reasonably simple attempt at fixing #460.
By moving the accept check to a place before the body check,
we can make it recoverable (the body check is irreversible,
so everything done after the body check has to fail fatally).
The advantage is that we can now specify routes offering
different content types modularly. Failure to match one
is not fatal, and will result in subsequent routes being
tried.
The disadvantage is that we hereby bump the error priority
of the 406 status code. If a request contains a bad accept
header and a bad body, we now get 406 rather than 400. This
deviates from the HTTP decision diagram we try to follow,
but seems like an acceptable compromise for now.
> Do the accept check before the body check.

- servant-client/servant-client.cabal
- servant/servant.cabal
Add missing changelogs and readme to cabal in `servant`, `servant-client` for hackage to display.
> Add missing changelogs and readme

- servant/test/Servant/API/ContentTypesSpec.hs
Test fails as:
Test suite doctests: RUNNING...
test/Servant/API/ContentTypesSpec.hs:31:18:
Ambiguous module name `Test.QuickCheck.Instances':
it was found in multiple packages:
checkers-0.4.4@check_A5bAKHstANbBRqwFoOaIKx testpack-2.1.3.0@testp_BjTqfpWNTOG5Lwlc3iqqG9 quickcheck-instances-0.3.12@quick_3Tkh09kYN8p78zxMKFPcZI
Test suite doctests: FAIL
Fixed by importing 'Test.QuickCheck.Instances' from "quickcheck-instances".
Signed-off-by: Sergei Trofimovich <siarheit@google.com>
> Fix doctests failure when testpack or checkers are installed

- servant-mock/servant-mock.cabal
This is causing build failures for some.
> Make servant-mock bounds match the other packages.

- servant-client/src/Servant/Client.hs
- servant-server/CHANGELOG.md
- servant-server/servant-server.cabal
- servant-server/src/Servant/Server.hs
- servant-server/src/Servant/Server/Internal/Context.hs
- servant-server/test/Servant/ArbitraryMonadServerSpec.hs
- servant/CHANGELOG.md
- servant/servant.cabal
- servant/src/Servant/Utils/Enter.hs
@soenkehahn and I were pairing on implementing `staticClient` function which will allow providing `BaseUrl` (or any argument in general) statically. After considering a few approaches we realised that `Enter` is already capable of achieving that (with an additional instance). Hence we decided to move `Enter` to `servant` package so that we could use it in `servant-client` without depending on `servant-server`. 
Please let us know your thoughts.
> Relocate Enter to `servant` package

- stack.yaml
All the missing extra-deps are now on Stackage, and the ones that were 
forced to a later version have also been updated, so the LTS should suffice.
> Update stack.yaml to LTS 6.0

- servant/src/Servant/API/ContentTypes.hs
The `MimeRender` instance in the documentation was incomplete and expected one more argument.
> Fix example `MimeRender` instance

- servant-client/src/Servant/Client.hs
- servant-docs/src/Servant/Docs/Internal.hs
- servant-docs/src/Servant/Docs/Internal/Pretty.hs
- servant-foreign/src/Servant/Foreign/Internal.hs
- servant-js/src/Servant/JS.hs
- servant-js/test/Servant/JSSpec/CustomHeaders.hs
- servant-server/src/Servant/Server.hs
- servant-server/src/Servant/Server/Internal.hs
I think `api` much more clearly expresses, what this really is.
> Rename type variables 'layout' and 'sublayout' to 'api'

- servant-client/servant-client.cabal
I'd like to add bounds for all other dependencies as well.
SItuations like are good example why you should have them. ping @hvr
> Add upper bounds http-client <0.5

- servant/src/Servant/Utils/Links.hs
> Add ‘HasLink’ instance for ‘BasicAuth’

- servant-client/servant-client.cabal
- servant-client/src/Servant/Common/Req.hs
- servant-server/servant-server.cabal
- servant/servant.cabal
This is an alternative PR to #538. I'd like to make a release to hackage that works with `http-client-0.5` soon. Since #538 contains other, more controversial changes I've created this PR in the hope in can be merged and released faster.
@haskell-servant/maintainers
> support http-client-0.5

- servant-client/test/ghcjs/stack-ghcjs.yaml
Unfortunately I couldn't reproduce a working `ghcjs` setup with the existing stack file. With this one it works again. But I suspect that `ghcjs` projects with stack files are not really reproducible yet. :(
> servant-client: update stack-ghcjs.yaml file for testsuite

- servant-js/examples/counter.hs
The Servant.JS Counter example was broken:
- `axios` was not completely applied; it now uses `defAxiosOptions` similarly to the `angular` example
- `OverloadedStrings` was required, but not included
> Fix servant-js examples

- .travis.yml
- scripts/ci-cron.sh
This uses the experimental cron job feature by travis: https://docs.travis-ci.com/user/cron-jobs/
It uses `stack` for the normal push-triggered CI.
The cron job script still uses `tinc`. We could switch this to `stack` once this is fixed: https://github.com/commercialhaskell/stack/issues/2475
> switch ci to stack and add ci cron job to test hackage breakage

- doc/tutorial/ApiType.lhs
Actually, I'm just trying to learn servant and I'm reading the doc for the first time. But this just looks like a typo to me.
> Fixed typo: s/real/realm/

- servant-docs/servant-docs.cabal
- servant-docs/src/Servant/Docs/Internal.hs
- servant-mock/servant-mock.cabal
- servant-mock/test/Servant/MockSpec.hs
- servant-server/servant-server.cabal
- servant-server/test/Servant/ServerSpec.hs
- servant/CHANGELOG.md
- servant/servant.cabal
- servant/src/Servant/API/ResponseHeaders.hs
Fixes servant/#581
* Version bump because this changes the API for GetHeaders
> Replace use of ToByteString with HttpApiData for GetHeaders

- doc/tutorial/Client.lhs
- servant-client/CHANGELOG.md
- servant-client/servant-client.cabal
- servant-client/src/Servant/Client.hs
- servant-client/src/Servant/Common/Req.hs
- servant-client/test/Servant/ClientSpec.hs
squashed version of https://github.com/haskell-servant/servant/pull/594
> changed ClientM to be a Reader of ClientEnv

- servant/CHANGELOG.md
- servant/src/Servant/API.hs
- servant/src/Servant/API/ResponseHeaders.hs
- servant/test/Servant/API/ResponseHeadersSpec.hs
Which allows not adding a header where a signature declares one, making
response headers optional. 
Fixes #621.
> Add noHeader function.

- servant-client/src/Servant/Client.hs
- servant-client/src/Servant/Common/Req.hs
- servant/servant.cabal
- servant/src/Servant/API/ContentTypes.hs
- servant/test/Servant/API/ContentTypesSpec.hs
WIP, not-tested
The situation is to be able to write:
``` hs
class Accept JPG where
contentTypes = "image/jpg" :| [ "image/jpeg" ]
```
---
this is different problem then in #522. Though with (too) clever `MimeUnrender` the problem there could be solved with this approach too.
> Allow multiple content-types for single Accept

- servant/servant.cabal
- servant/src/Servant/API/ContentTypes.hs
- servant/test/Servant/API/ContentTypesSpec.hs
- stack-ghc-7.8.4.yaml
Follow-up to #614, makes possible to resolve problem in #552 without complicating general `servant-client` code: the problem solution will go into client application.
/cc @jkarni @soenkehahn @cdepillabout 
I added an `aeson-compat` dependency, as it makes test pass on ghc-7.8. With old enough `aeson`, vanilla `decode` doesn't accept top-level scalars (i.e. accepts only arrays and objects, which leads to wtf-situations). Alternatively one could bump aeson version for tests.
> Mime unrender multiple

- servant-client/servant-client.cabal
- servant-client/src/Servant/Client.hs
- servant-client/src/Servant/Common/Req.hs
NOTE: This is most probably not ready to be merged yet. It's primarily to aid the discussion in #656.
Rather than hard-coding the `RequestBodyLBS` constructor and be
limited to lazy bytestrings, the new function `setReqBody` just
takes any value of type `RequestBody`.
This has the advantage the we can use streaming request bodies
such as for example constructed by the `streamFile` function in
http-client.
> servant-client: generalize the function to set the request body

- servant-docs/src/Servant/Docs/Internal.hs
- servant-foreign/src/Servant/Foreign/Internal.hs
- servant/CHANGELOG.md
- servant/servant.cabal
- servant/src/Servant/API/TypeLevel.hs
- servant/src/Servant/Utils/Links.hs
- servant/test/Servant/Utils/LinksSpec.hs
Closes #305.
I need to write some tests, otherwise, should be complete.
> Servant.API.TypeLevel

- servant-client/CHANGELOG.md
- servant-client/servant-client.cabal
- servant-client/src/Servant/Client/Generic.hs
- servant-client/test/Servant/ClientSpec.hs
This PR is related to #344 and adds the class that matches client functions generated using `client` with data structure (its representation as sum of products).
The structure itself has to be written manually (no TH used here), but we avoid pattern-matching, which is replaced with just one line of code.
> Generic client

- servant-server/servant-server.cabal
- servant-server/src/Servant/Server/Internal.hs
- servant-server/src/Servant/Server/Internal/RoutingApplication.hs
- servant-server/test/Servant/Server/Internal/RoutingApplicationSpec.hs
Rebase of #622, with tests changed to use `IORef`
> Delayed cleanup ioref tests

- servant-server/test/Servant/ServerSpec.hs
- servant/CHANGELOG.md
- servant/src/Servant/API/ContentTypes.hs
- servant/test/Servant/API/ContentTypesSpec.hs
This resolves #263.
But, it's the revert of https://github.com/haskell-servant/servant/commit/99374c5868b7e20f526532d7bcbe917c55d11ad1 by @jkarni. Can you comment why it was introduced, so we don't go back and forth?
> Change JSON content type to add the charset

- servant-server/CHANGELOG.md
- servant-server/src/Servant/Server/Internal.hs
- servant-server/src/Servant/Server/Internal/RoutingApplication.hs
- servant-server/test/Servant/Server/ErrorSpec.hs
- servant-server/test/Servant/Server/Internal/RoutingApplicationSpec.hs
- servant-server/test/Servant/ServerSpec.hs
- servant/src/Servant/API/ContentTypes.hs
> Throw error on param parse failure.

- servant-server/test/Servant/Server/RouterSpec.hs
Relating to the email discussion.
We do merge segments, even when there are `QueryParam`. See `type PermuteRef`.
> Add test illustrating that query params don't affect router grouping

- doc/requirements.txt
* Includes [Haskell types fix by @teh](https://bitbucket.org/birkenfeld/pygments-main/pull-requests/685/two-haskell-fixes/diff)
* Local docs build then exhibit proper Haskell highlighting including type literals etc:
Fixes #359
> Use newer release of Pygments

- servant/src/Servant/Utils/Links.hs
I needed this instance for routes authenticated with `servant-auth-cookie` and thought I might as well submit it here. Let me know if there is anything I've overlooked and I'll try to fix it.
> Add HasLink instance for AuthProtect.

- servant-foreign/src/Servant/Foreign/Internal.hs
`servant-foreign` currently fails to build with GHC 8.2. This is because the validity checking for associated type family instances [tightened up](https://ghc.haskell.org/trac/ghc/wiki/Migration/8.2?version=19#Associatedtypefamilyinstancesarepickier) a bit, and now require using the same type variables in the associated family instance as in the instead head itself.
Luckily, this amounts to a single-character change.
> Make servant-foreign build on GHC 8.2

- servant-server/CHANGELOG.md
- servant-server/src/Servant/Server/Internal.hs
- servant-server/src/Servant/Server/Internal/RoutingApplication.hs
- servant-server/test/Servant/Server/Internal/RoutingApplicationSpec.hs
- servant-server/test/Servant/ServerSpec.hs
Similar to #649 and #670, header handling ignores parse errors and just passes Nothing as though the header isn't present. 
This pull requests adds a headersD block to Delayed and throws 400 when header parsing fails.
> Throw 400 on header parse failure

- servant-server/src/Servant/Server.hs
- servant-server/test/Servant/ArbitraryMonadServerSpec.hs
- servant/src/Servant/Utils/Enter.hs
> Redo Enter

- doc/tutorial/Client.lhs
- doc/tutorial/index.rst
* Use suggestion in #606 to document pattern matching client behaviour better
* Helpful suggestion of reading in order in the index
* A couple of extra internal links
* Fix some typos / punctuation.
Fixes #606
> Improve Client docs

- servant/src/Servant/API/RemoteHost.hs
- servant/src/Servant/API/ResponseHeaders.hs
Here is a patch for a few typos:
- extra pipe in RemoteHost.hs
- missing apostrophe for `addOptionalHeader` class method
- `hdr` is displayed as an anchor
> fix minor typos

- servant/src/Servant/API/ContentTypes.hs
- stack.yaml
Just a proof-of-concept. It compiles, but I'm not sure how to check if it works / write a test for it.
I had to up the stackage resolver, otherwise base would be < 4.9.0
Relevant issue: https://github.com/haskell-servant/servant/issues/576
> TypeError annotations for AllCTRender

- servant-client/src/Servant/Common/Req.hs
The derived client for an API containing `Capture` has a bug: it does not
escape characters, so that if the string is "a/b", the URL becomes
`".../a/b/..."` instead of `".../a%2Fb/..."`, causing the corresponding servant
server to return a 404.
This relies on https://github.com/fizruk/http-api-data/pull/47
> Make sure path components get escaped

- servant-client/src/Servant/Common/Req.hs
- servant-client/test/Servant/ClientSpec.hs
Sometimes I find it hard to figure out what API call caused the error that servant-client throws, this PR fixes that by including the request in the error.
> Include the request that failed in FailureResponse.

- doc/tutorial/ApiType.lhs
- doc/tutorial/Client.lhs
- doc/tutorial/Docs.lhs
- doc/tutorial/Javascript.lhs
- doc/tutorial/Server.lhs
- servant-client/src/Servant/Client.hs
- servant-client/test/Servant/ClientSpec.hs
- servant-docs/src/Servant/Docs/Internal.hs
- servant-docs/test/Servant/DocsSpec.hs
- servant-foreign/src/Servant/Foreign/Internal.hs
- servant-foreign/test/Servant/ForeignSpec.hs
- servant-server/src/Servant/Server.hs
- servant-server/src/Servant/Server/Internal.hs
- servant-server/test/Servant/ServerSpec.hs
- servant/servant.cabal
- servant/src/Servant/API.hs
- servant/src/Servant/API/Empty.hs
- servant/src/Servant/API/Internal/Test/ComprehensiveAPI.hs
- servant/test/Servant/Utils/LinksSpec.hs
This is for where you want to compose an API out of bits that come from various sources. For example, we have a Servant API, `CommonAPI`, and a function that has a type rather like this:
defaultMain :: HasServer specialAPI => Proxy specialAPI -> Server specialAPI -> ... -> IO a
the purpose of which is to serve `CommonAPI :<|> specialAPI`, plus a bunch of other common setup/teardown code. Most of the time there's interesting stuff in `specialAPI`, but in one or two cases there's nothing much to put there.
Morally speaking, this would be a unit for the `:<|>` operator (up to isomorphism).
This issue follows a [discussion on the mailing list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/haskell-servant/J76EcFgr8m8/Rahw0sriBAAJ) concluding with @alpmestan saying:
> …
> Add a type representing an empty API

- servant-docs/src/Servant/Docs/Internal.hs
As reported in #754, `HasDocs` instance of `ReqBody` was dropping samples other
than the first one. With this patch we show at most `_maxSamples` samples for
`ReqBody`, and also include the sample title in the docs.
> Don't drop samples in `HasDocs ReqBody` instance

- doc/tutorial/ApiType.lhs
I simply removed an extraneous “the”, hope this nitpicking isn't annoying to you :)
> Fix typo in ApiType.lhs

- servant-docs/src/Servant/Docs/Internal.hs
This PR removes `#### Authentication` section when `authInfo` in `Action` is empty.
Before:
~~~
$ stack runghc example/greet.hs | head -n 25                                                                                                                  
Hello there.
As documentation is usually written for humans, it's often useful to introduce concepts with a few words.
You'll also note that multiple intros are possible.
Clients must supply the following data
- Supported content types are:
- `application/json;charset=utf-8`
- `application/json`
~~~
After:
~~~
$ stack runghc example/greet.hs | head -n 25 
Hello there.
As documentation is usually written for humans, it's often useful to introduce concepts with a few words.
You'll also note that multiple intros are possible.
- Supported …
> Improve authStr in markdown

- servant-docs/src/Servant/Docs.hs
I'm assuming that they're not meant to be just in `.Internal`.
> Export authentication-related types/lenses

- servant-docs/src/Servant/Docs/Internal.hs
Currently, it appears after the notes, authentication and capture
information... such that if any of those exist, then the list of
header sensitivity will appear to be an item of one of the previous
ones (as they provide Markdown headers).
> Move location of header information

- servant-docs/src/Servant/Docs/Internal.hs
> Document the type of endpoint a parameter belongs to

- servant-docs/CHANGELOG.md
As requests by @phadej in #790 
I went with `0.11.1` for the version as additional entities are exported, but no breaking API changes.
> Add Changelog entries for my recent pull requests

- servant-client/src/Servant/Client.hs
- servant-docs/src/Servant/Docs/Internal.hs
- servant-docs/test/Servant/DocsSpec.hs
- servant-foreign/src/Servant/Foreign/Internal.hs
- servant-server/src/Servant/Server/Internal.hs
- servant-server/test/Servant/ServerSpec.hs
- servant/servant.cabal
- servant/src/Servant/API.hs
- servant/src/Servant/API/Description.hs
- servant/src/Servant/API/Internal/Test/ComprehensiveAPI.hs
This PR adds combinators discussed in https://github.com/haskell-servant/servant-swagger/issues/60. They allow you to add documentation for API endpoints right in the type declaration.
Both `Description` and `Summary` are needed for different `HasSwagger` instances:
```haskell
instance (KnownSymbol desc, HasSwagger api) => HasSwagger (Description desc :> api) where
toSwagger _ = toSwagger (Proxy @api)
& allOperations.description %~ (Just (Text.pack (symbolVal (Proxy @desc))) <>)
instance (KnownSymbol desc, HasSwagger api) => HasSwagger (Summary desc :> api) where
toSwagger _ = toSwagger (Proxy @api)
& allOperations.summary %~ (Just (Text.pack (symbolVal (Proxy @desc))) <>)
```
> Description and Summary combinators

- doc/tutorial/Docs.lhs
- doc/tutorial/tutorial.cabal
- servant-docs/CHANGELOG.md
- servant-docs/servant-docs.cabal
- servant-docs/src/Servant/Docs.hs
- servant-docs/src/Servant/Docs/Internal.hs
- stack-ghc-7.8.4.yaml
If an instance of `Accept` has multiple `contentTypes`, then previously each one was listed individually, even though the contents were identical.
This attempts to fix that, but isn't perfect: it groups identical rendered output together (which actually may be sufficient from a documentation point of view in indicating that there is no conceptual difference in how the values are represented).
Furthermore, to prevent generated documentation from becoming long, it is possible to specify whether all or just one mime-type of each example is shown.
> Multiple content types

- .travis.yml
- README.md
- cabal.project
- doc/tutorial/tutorial.cabal
- servant-client-core/CHANGELOG.md
- servant-client-core/servant-client-core.cabal
- servant-client/CHANGELOG.md
- servant-client/servant-client.cabal
- servant-docs/CHANGELOG.md
- servant-docs/servant-docs.cabal
- servant-foreign/CHANGELOG.md
- servant-foreign/servant-foreign.cabal
- servant-server/CHANGELOG.md
- servant-server/servant-server.cabal
- servant/CHANGELOG.md
- servant/servant.cabal
The changelog for `servant` contains changes across core packages,
as we release them as a suite.
Also added links to the GitHub master as we might update entries
for old versions, as changelogs are written by humans.
> Bump versions and update changelogs.

- .travis.yml
- servant-client/CHANGELOG.md
- servant-client/servant-client.cabal
- servant-client/src/Servant/Client/Internal/HttpClient.hs
Fixes #858 . The bug was introduced in servant-client-core refactor
(servant-client-0.12).
See https://github.com/haskell-servant/servant/blob/8973cf56f1feea8830212c05ca2c2682e398499e/servant-client/src/Servant/Common/Req.hs#L151-L179
for the unbroken variant in servant-client-0.11
> Send Accept header in servant-client

- servant-foreign/src/Servant/Foreign/Internal.hs
- servant-foreign/test/Servant/ForeignSpec.hs
This fix exposes routes containing `Header _ a :> …` as `Maybe a …`. A typical problem is when you want to make request to such routes without using a header (typical when you’re working with the `Authorization` header, for instance).
I’m also making a PR to the `servant-elm` project.
> Temporary fix for Header.

- servant-client-ghcjs/servant-client-ghcjs.cabal
I haven’t done particularly extensive testing against `0.12` but it definitely does build and in my limited testing it also seems to work just fine.
> Bump servant-client-core upperbound in servant-client-ghcjs

- servant/src/Servant/Utils/Links.hs
- Reverting (and re-introducing different bug): *bad*
- Fixing for all: *good*
`Param` is unfortunately exposed, so I don't change it. This way this commit is backportable to 0.12.
> Fix #835. Use Escaped to prevent double-escaping

- servant/src/Servant/API/Capture.hs
- servant/src/Servant/API/QueryParam.hs
- servant/src/Servant/API/ReqBody.hs
- servant/src/Servant/API/Stream.hs
- servant/src/Servant/API/Sub.hs
- servant/src/Servant/API/Verbs.hs
- servant/test/Servant/Utils/LinksSpec.hs
The resulting errors are ludicrously better with `( :: *)` signatures:
Breaking the greet example by doing
```
:<|> "greet" :> Capture "greetid" Text :> Delete '[JSON]
```
instead of
```
:<|> "greet" :> Capture "greetid" Text :> Delete '[JSON] NoContent
```
Before yielded
```
/home/mgsloan/oss/haskell/servant/servant-docs/example/greet.hs:94:5: error:
• Could not deduce: Servant.API.TypeLevel.Or
(Servant.API.TypeLevel.IsIn
("greet" :> (Capture "greetid" Text :> Delete '[JSON] NoContent))
("hello"
:> (Capture "name" Text
:> (QueryParam "capital" Bool :> Get '[JSON, PlainText] Greet))))
(Servant.API.TypeLevel.Or
(Servant.API.TypeLevel.IsIn
(Capture "greetid" Text :> Delete '[JSON] NoContent)
(ReqBody '[JSON] Greet
:> Post '[JSON] (Headers '[Header "X-Example" Int] Greet))) …
```
> Kinder type checking

- servant-client-core/src/Servant/Client/Core/Internal/HasClient.hs
- servant-docs/src/Servant/Docs/Internal.hs
- servant-docs/test/Servant/DocsSpec.hs
- servant-foreign/servant-foreign.cabal
- servant-foreign/src/Servant/Foreign/Internal.hs
- servant-foreign/test/Servant/ForeignSpec.hs
- servant-server/src/Servant/Server/Internal.hs
- servant-server/test/Servant/ServerSpec.hs
- servant/servant.cabal
- servant/src/Servant/API.hs
- servant/src/Servant/API/Header.hs
- servant/src/Servant/API/Internal/Test/ComprehensiveAPI.hs
- servant/src/Servant/API/Modifiers.hs
- servant/src/Servant/API/QueryParam.hs
- servant/src/Servant/API/ReqBody.hs
- servant/src/Servant/API/ResponseHeaders.hs
- servant/src/Servant/Utils/Links.hs
- servant/test/Servant/Utils/LinksSpec.hs
Implements modifiers #856.
`QueryParams`? `Required` -> `NonEmpty a`?
-  `Capture` can also be lenient, but I'll leave it for now, but by definition they are always required.
There's some info in the commit messages.
- https://github.com/haskell-servant/servant/issues/862
- When `ReqBody` is amended, will solve https://github.com/haskell-servant/servant/issues/793
- Supersedes https://github.com/haskell-servant/servant/pull/256
> Servant.API.Modifiers

- doc/tutorial/tutorial.cabal
- servant-client-core/servant-client-core.cabal
- servant-client/servant-client.cabal
- servant-docs/servant-docs.cabal
- servant-foreign/servant-foreign.cabal
- servant-foreign/test/Servant/ForeignSpec.hs
- servant-server/servant-server.cabal
- servant/servant.cabal
- servant/test/Servant/Utils/LinksSpec.hs
- stack.yaml
- `text` is already 1.2.3.0 as https://github.com/fpco/stackage/issues/3147 is resolved AFAICS, though not closed.
- `http-types` bound is surprisingly low due: https://github.com/fpco/stackage/issues/2976
---
@alp and other @haskell-servant/maintainers: I'd like to try this bounds schema. It's less aggressive than "lowest versions there is build-plan for", but lessens maintaining burden (we have e.g. `MIN_VERSION_http_types` and `MIN_VERSION_wai_app_static` now, which I'd like to get rid off, we really don't test "other branch" that well)
> Bump lower bounds

- .travis.yml
- cabal.project
- doc/cookbook/basic-auth/basic-auth.cabal
- doc/cookbook/db-postgres-pool/db-postgres-pool.cabal
- doc/cookbook/db-sqlite-simple/db-sqlite-simple.cabal
- doc/cookbook/jwt-and-basic-auth/jwt-and-basic-auth.cabal
- servant-client-core/servant-client-core.cabal
- servant-client-ghcjs/servant-client-ghcjs.cabal
- servant-client/servant-client.cabal
- servant-docs/servant-docs.cabal
- servant-foreign/servant-foreign.cabal
- servant-server/servant-server.cabal
- servant-server/test/Servant/ServerSpec.hs
- servant/servant.cabal
- stack.yaml
- ~~WIP: pending http-api-data release~~
- ~~TODO: remove MIN_VERSION_http_types~~
- There have been 3 major releases of http-types:
- 0.10 change name of variable
- 0.11 lowercase escaped URIs
- 0.12 uppercase escaped URIs
- It's easier for us to support only latest, migration from 0.9/0.10 to 0.12
is trivial for the downstream. 0.11 may cause semantic (non-type-error) breakage somewhere.
- ~TODO: update `stack.yaml`~
> Bump lower bound of http-types >= 0.12

- servant-client/servant-client.cabal
- servant-docs/servant-docs.cabal
- servant-server/servant-server.cabal
- servant/servant.cabal
- stack.yaml
fixes https://github.com/fpco/stackage/issues/3337
I didn't actually test an app with the patched servant, I only ran the tests, but since it all compiles and the tests pass, it should be OK I assume.
> relax the aeson constraint, allow 1.3.0.0

- servant-client-core/servant-client-core.cabal
- servant-client-core/src/Servant/Client/Core/Internal/ClientF.hs
- servant-client-core/src/Servant/Client/Core/Internal/RunClient.hs
- servant-client-core/src/Servant/Client/Free.hs
- servant-client-ghcjs/src/Servant/Client/Internal/XhrClient.hs
- servant-client/src/Servant/Client/Internal/HttpClient.hs
this is useful in testing, it nothing else.
> Add Servant.Client.Free

- servant-client-core/src/Servant/Client/Core/Internal/Request.hs
- servant-client-ghcjs/src/Servant/Client/Internal/XhrClient.hs
- servant-client/servant-client.cabal
- servant-client/src/Servant/Client/Internal/HttpClient.hs
- servant-client/test/Servant/ClientSpec.hs
- servant-client/test/Servant/StreamSpec.hs
- stack-ghcjs.yaml
- stack.yaml
Fixes #886.
I also added tests to check that `Stream` ran in constant memory while I was at it.
> Streaming request body for servant-client-core

- servant-server/src/Servant/Server/Internal.hs
- servant-server/test/Servant/Server/ErrorSpec.hs
In case that a sub-server doesn't support the content-type specified
in the request invoke `delayedFail` instead of `delayedFailFatal` in
order to give the chance to other sub-servers to handle the request.
Right now when you want to implement a server that supports multiple
content types on the same path with different handlers you muse use
the `Raw` and implement a Wai app. Otherwise the first sub-server, if
you try to use Servant type system to define the API it will either
match the content type of the request and serve a response or return
a 415 error.
This update (in theory) makes it possible to serve multiple
content-types with different APIs and their corresponding handlers.
> Update request content-type handling

- doc/cookbook/cabal.project
- doc/cookbook/index.rst
- doc/cookbook/pagination/Pagination.lhs
- doc/cookbook/pagination/pagination.cabal
As proposed in #125, here's a short introduction to [servant-pagination](https://hackage.haskell.org/package/servant-pagination-2.1.0). 
Feedback is welcome :)
> add recipe introducing servant-pagination

- servant-client/README.lhs
- servant-client/README.md
- servant-client/servant-client.cabal
`README.md` was outdated, so I've brought it up in sync with the codebase and made sure it won't happen again.
I've tried to keep example in sync with http://haskell-servant.readthedocs.io/en/stable/tutorial/Client.html but with some simplification so that it's closer to a hello world.
> servant-client: update README.md and test it

- servant-server/src/Servant/Utils/StaticFiles.hs
This simply seems possible without breaking anything, so why not?
I've only tried to build servant-server and the tutorial. Let's see what CI says, but it seems to me like the monad is never going to be ambiguous, unless you have a single handler which does file serving, but you still use another monad and call `hoistServer` on your handler, maybe?
Thoughts?
> servant-server: make file-serving functions polymorphic in the monad

- doc/tutorial/ApiType.lhs
- servant-client/test/Servant/StreamSpec.hs
- servant-server/src/Servant/Server/Internal.hs
- servant/src/Servant/API.hs
- servant/src/Servant/API/Stream.hs
Currently it is not possible to write an instance for `StreamGenerator` for conduit, despite the comment saying otherwise.
Furthermore you cannot use Streams that use a ReaderT IO stack.
This PR trys to solve that
DISCLAIMER: I have to idea what I'm doing
> Change definition of StreamGenerator

- .travis.yml
- cabal.project
- doc/cookbook/basic-auth/basic-auth.cabal
- doc/cookbook/db-postgres-pool/db-postgres-pool.cabal
- doc/cookbook/db-sqlite-simple/db-sqlite-simple.cabal
- doc/cookbook/file-upload/file-upload.cabal
- doc/cookbook/https/https.cabal
- doc/cookbook/jwt-and-basic-auth/jwt-and-basic-auth.cabal
- doc/cookbook/pagination/pagination.cabal
- doc/cookbook/structuring-apis/structuring-apis.cabal
- doc/cookbook/using-custom-monad/using-custom-monad.cabal
- doc/tutorial/tutorial.cabal
- servant-client-core/servant-client-core.cabal
- servant-client/servant-client.cabal
- servant-docs/servant-docs.cabal
- servant-foreign/servant-foreign.cabal
- servant-server/servant-server.cabal
- servant/servant.cabal
- servant/src/Servant/Utils/Links.hs
- servant/test/Servant/Utils/LinksSpec.hs
> Add safeLink'

- servant-client-core/src/Servant/Client/Core/Internal/HasClient.hs
- servant-server/src/Servant/Server/Internal.hs
- servant/src/Servant/API/Stream.hs
Currently streaming endpoints are always returning `200 OK`. With this it is not possible to implement e.g. Range Requests, as those need to return `206 Partial Content`. This PR changes this.
> Allow to specify a status for streaming endpoints

- servant-server/test/Servant/ServerSpec.hs
This was missed due to an oversight.
Adding an explicit export list to `ServantSpec.hs` would allow a computer to catch these problems. I haven't done that here.
> Run `captureAllSpec`

- servant-client-core/servant-client-core.cabal
- servant-client-core/src/Servant/Client/Core/Internal/HasClient.hs
- servant-client/test/Servant/StreamSpec.hs
- servant-docs/src/Servant/Docs/Internal.hs
- servant-foreign/src/Servant/Foreign/Internal.hs
- servant/src/Servant/API.hs
- servant/src/Servant/API/Internal/Test/ComprehensiveAPI.hs
- servant/src/Servant/API/Stream.hs
- servant/src/Servant/Utils/Links.hs
I'd like to have
```haskell
"stream" :> StreamGet NewlineFraming '[PlainText] [Text] -- lines
```
Also having `StreamingReqBody` should be in `servant`
> Add toStreamGenerator (NonEmpty a) instance

- .travis.yml
- cabal.project
- doc/cookbook/index.rst
- doc/cookbook/using-free-client/UsingFreeClient.lhs
- doc/cookbook/using-free-client/using-free-client.cabal
I'm too easily nerd-snipped, there should be a price tag for that.
> Add 'using free client' recipe

- README.md
It is out of date and we already have enough to do during releases to be updating this table, I think.
> Remove version history from README.md

- doc/examples.md
Hello,
I just finished a working website with Servant, Elm 0.19, YeshQL / PostgreSQL, and I was wondering if you were interested to list it in the documentation.
I used a lot the servant documentation and the github search when I was learning Servant. This project will maybe help others learner.
In any case, thanks a bunch for Servant! :)
> Documentation, adding full website project with servant,auth,elm,yeshql,postgresql

- servant/servant.cabal
- servant/src/Servant/API/Alternative.hs
These mirror the corresponding instances for (,)
> Add bifunctors instances for Servant.API.Alt

- .travis.yml
- cabal.project
- doc/cookbook/cabal.project
- doc/cookbook/curl-mock/CurlMock.lhs
- doc/cookbook/curl-mock/curl-mock.cabal
- doc/cookbook/index.rst
With help from `alp` on irc I built a little tool that creates mock curl calls for post requests with request bodies.
The result is baked into this cookbook example. 
Please do not hesitate to tell me where my haskell could be improved as this is the first significant piece of haskell I've written.
> curl-mock cookbook example

- cabal.project
- doc/cookbook/cabal.project
- doc/cookbook/index.rst
- doc/cookbook/testing/Testing.lhs
- doc/cookbook/testing/testing.cabal
Hi Servant Team,
This is the testing-cookbook PR that I mentioned to @alpmestan on IRC. I *think* it includes all the examples he had in mind, but it could include a lot more content, depending on how long we want it to be. 
It was tough, honestly, not to just go on and on and on with this one, but hopefully it shows a handful of strategies that will prove useful to the audience.
- Add testing cookbook (cabal file and `Testing.lhs`)
- Update cookbook/cabal.project
- Update cabal.project
- Add to index.rst
- Didn't include anything about testing against a database (aside from my Elasticsearch example, which maybe counts...).
- In spite of my instincts, I left some failing tests in there (see output below) because I figured it would be more instructive to see the output for failing tests?
- …
> Add Testing cookbook

- servant/src/Servant/API/ResponseHeaders.hs
Required for https://github.com/plow-technologies/servant-streaming/pull/14/files
PS: there are a few other typeclasses in that module that would be useful to be exported.
> ResponseHeaders: export GetHeaders'

- doc/cookbook/generic/Generic.lhs
- servant-server/src/Servant/Server/Generic.hs
Closes https://github.com/haskell-servant/servant/issues/1055
> genericServeT and docs on using a custom monad with generics

- servant-docs/example/greet.md
- servant-docs/src/Servant/Docs/Internal.hs
The code indention of the Response does not get correctly rendered on github.
> Fix markdown indentation and compilation warning

- servant-server/src/Servant/Server/Internal/Handler.hs
`exceptions-0.10` has introduced a working `MonadMask` instancesfor `ExceptT` so we can now also provide this for `Handler`. `servant-server` already has a lower bound of `>= 0.10` on `exceptions`, so this doesn’t impose any additional restrictions.
> Add MonadMask instance for Handler

- servant-client/test/Servant/ClientSpec.hs
- servant-docs/test/Servant/DocsSpec.hs
- servant-foreign/test/Servant/ForeignSpec.hs
- servant-server/test/Servant/ServerSpec.hs
- servant/servant.cabal
- servant/src/Servant/API/Internal/Test/ComprehensiveAPI.hs
- servant/src/Servant/Test/ComprehensiveAPI.hs
- servant/test/Servant/LinksSpec.hs
We cannot simply tweak it, that will break tests of other packages.
Including packages not in this repository.
> Make ComprehensiveAPI part of public API

- servant-foreign/servant-foreign.cabal
- servant-foreign/src/Servant/Foreign.hs
- servant-foreign/src/Servant/Foreign/Internal.hs
This is three patches, to `servant-foreign`, `servant-multipart`, and `servant-js`.
https://github.com/haskell-servant/servant-multipart/compare/master...afcady:multipart-foreign?expand=1
https://github.com/haskell-servant/servant/compare/master...afcady:multipart-foreign?expand=1
https://github.com/haskell-servant/servant-js/compare/master...afcady:multipart-foreign?expand=1
The patch to `servant-foreign` adds a Boolean field to the `Req` type specifying whether the request body is JSON (as is currently assumed).  The patch to `servant-multipart` implements a HasForeign instance that sets this field to `False`.  The patch to `servant-js` changes the output of `vanillaJS` when the flag is false, so that `JSON.stringify()` does not get called on the body and the content-type is not set to …
> Implement HasForeign instance

- doc/cookbook/basic-streaming/Streaming.lhs
- doc/tutorial/Client.lhs
- doc/tutorial/tutorial.cabal
- servant-client-core/servant-client-core.cabal
- servant-client-core/src/Servant/Client/Core.hs
- servant-client-core/src/Servant/Client/Core/Internal/HasClient.hs
- servant-client-core/src/Servant/Client/Core/Internal/Request.hs
- servant-client-core/src/Servant/Client/Core/Internal/RunClient.hs
- servant-client-ghcjs/src/Servant/Client/Internal/XhrClient.hs
- servant-client/servant-client.cabal
- servant-client/src/Servant/Client.hs
- servant-client/src/Servant/Client/Internal/HttpClient/Streaming.hs
- servant-client/src/Servant/Client/Streaming.hs
- servant-client/test/Servant/ClientSpec.hs
- servant-client/test/Servant/StreamSpec.hs
- servant-conduit/example/Main.hs
- servant-docs/golden/comprehensive.md
- servant-machines/example/Main.hs
- servant-pipes/example/Main.hs
- servant/src/Servant/Test/ComprehensiveAPI.hs
- servant/test/Servant/LinksSpec.hs
> Separate streaming client

- doc/tutorial/Server.lhs
Change the app4 curl example to match the API definition.
As defined, it does not return "hi" and instead always returns true.
> Fix the tutorial app4 curl example

- servant-client-core/src/Servant/Client/Core/Internal/HasClient.hs
- servant-client/test/Servant/StreamSpec.hs
@domenkozar can you check this works for your use-case?
Fixes #1091
> Oleg testcase 1091

- servant-client-core/src/Servant/Client/Core/Internal/Request.hs
- servant-client/src/Servant/Client/Internal/HttpClient.hs
- servant-client/test/Servant/ClientSpec.hs
fixes #807
Previously, there were two levels of `SomeException` (see #714). A
test makes sure there is only one level of wrapping.
> keep structured exceptions in `ConnectionError`

- .travis.yml
- cabal.haskell-ci
- doc/cookbook/basic-auth/basic-auth.cabal
- doc/cookbook/basic-streaming/basic-streaming.cabal
- doc/cookbook/curl-mock/curl-mock.cabal
- doc/cookbook/db-postgres-pool/db-postgres-pool.cabal
- doc/cookbook/db-sqlite-simple/db-sqlite-simple.cabal
- doc/cookbook/file-upload/file-upload.cabal
- doc/cookbook/generic/generic.cabal
- doc/cookbook/hoist-server-with-context/hoist-server-with-context.cabal
- doc/cookbook/https/https.cabal
- doc/cookbook/jwt-and-basic-auth/jwt-and-basic-auth.cabal
- doc/cookbook/pagination/pagination.cabal
- doc/cookbook/sentry/sentry.cabal
- doc/cookbook/structuring-apis/structuring-apis.cabal
- doc/cookbook/testing/testing.cabal
- doc/cookbook/using-custom-monad/using-custom-monad.cabal
- doc/cookbook/using-free-client/using-free-client.cabal
- doc/tutorial/tutorial.cabal
- servant-client-core/servant-client-core.cabal
- servant-client/servant-client.cabal
- servant-conduit/servant-conduit.cabal
- servant-docs/servant-docs.cabal
- servant-foreign/servant-foreign.cabal
- servant-http-streams/servant-http-streams.cabal
- servant-machines/servant-machines.cabal
- servant-pipes/servant-pipes.cabal
- servant-server/servant-server.cabal
- servant/servant.cabal
- Update GHC-8.6.2 to GHC-8.6.3
- Build cookbook only with GHC-8.4.4 and GHC-8.6.3, thus
making 8.0 and 8.2 jobs a little faster
> Update travis once again

- servant-server/CHANGELOG.md
Just fix for [servant-server/CHANGELOG.md](https://github.com/haskell-servant/servant/blob/94e0acc3d265f1a7e3c4fb7f8c60fc4e502277c6/servant/CHANGELOG.md), no code modified.
> Fix URLs to pull requests in servant-server/CHANGELOG.md

- servant-server/servant-server.cabal
- servant/servant.cabal
> Allow http-api-data 0.4.1

- doc/tutorial/index.rst
Follows up conversations around adding stack steps to the tutorial project documentation [here](https://github.com/haskell-servant/servant/issues/1101)
> add stack to tutorial docs

- doc/cookbook/cabal.project
- doc/cookbook/db-mysql-basics/MysqlBasics.lhs
- doc/cookbook/db-mysql-basics/mysql-basics.cabal
- doc/cookbook/index.rst
Contributes a basic mysql-backed API with basic CRUD functionalities.
> Add mysql cookbook example

- servant/servant.cabal
Useful for cross-compilation. Otherwise, `callCabal2nix` fails when compiling with `pkgs.pkgsCross.iphone64.haskell.packages.integer-simple.ghc865`
> Remove unused extensions from servant cabal file.

- changelog.d/issue1206
- doc/tutorial/Authentication.lhs
- doc/tutorial/Client.lhs
Fixes broken links in both https://haskell-servant.readthedocs.io/en/stable/tutorial/Client.html and https://haskell-servant.readthedocs.io/en/stable/tutorial/Authentication.html .
> Fixes issue #1206 by updating broken links in tutorial.

- .travis.yml
- cabal.project
jsdom stuff takes too long to compile, and even then I think `servant-jssaddle` doesn't belong into this repository. I'll move that package to its own repository under haskell-servant org.
> Try to fix CI: remove servant-jssaddle, install npm

- changelog.d/pull1238
- servant-client-core/servant-client-core.cabal
- servant-client-core/src/Servant/Client/Core/Request.hs
- servant-client-core/test/Servant/Client/Core/RequestSpec.hs
Prevent credentials leaking in exception messages.
> servant-client-core: Redact Authorization header

- changelog.d/issue1240
- servant-docs/src/Servant/Docs/Internal.hs
- servant-docs/test/Servant/DocsSpec.hs
Partially fixes #1240 .
Servant supports defining the same route multiple times with different
content-types and result-types, but servant-docs was only documenting
the first of copy of such duplicated routes. It now combines the
documentation from all the copies.
Unfortunately, it is not yet possible for the documentation to specify
multiple status codes. That's why this is only a partial fix for #1240 .
> merge documentation from duplicate routes

- servant-server/src/Servant/Server/Generic.hs
This commit adds an explanation and a link to the Servant Cookbook
to `genericServerT`.
Moreover, the `genericServer` and `genericServe`'s haddocks are
slightly edited to add a missing 'a'.
> docs(generic): Improve the documentation for `genericServerT`

- .gitignore
- default.nix
- nix/nixpkgs.json
cc @fizruk @arianvp @fisx 
We can add `pkgs.haskell.lib.sdistTarball` as well for easy generation of release tarballs.
> Build servant repo with nix.

- servant-docs/README.md
I found a few problems in the code sample of servant-docs, so I fixed them for later users:
- `toSample` function no longer exists
- `DocQueryParam` needs a `ParamKind` argument
- `RQBody` should be `ReqBody`
- added implicit imports for better readability
Related issue:
https://github.com/haskell-servant/servant/issues/1212
> Fix servant-docs code sample in README

- servant-docs/src/Servant/Docs/Internal.hs
As the title says, adds an instance for `ToSample (NonEmpty a)` given we have an instance for `ToSample a`.
> Add instance for ToSample NonEmpty

- servant-client-core/servant-client-core.cabal
Fixes #1334 
I have checked locally that `servant-client-core` can build with `base16-bytestring` 1.1 without any modifications. According to the PVP I think we could loosen it further to `< 2`, but `< 1.2` works for now.
> Loosen bound on base16-bytestring

- servant-client-core/servant-client-core.cabal
We should make a cabal revision for this too I suppose. Looks like this was an oversight
I don't know how to do this on hackage yet; but would be happy if someone could show me
> servant-client-core: depend on 0.18.2

- servant-client-core/servant-client-core.cabal
- servant-client-ghcjs/servant-client-ghcjs.cabal
- servant-client/servant-client.cabal
- servant-conduit/servant-conduit.cabal
- servant-docs/servant-docs.cabal
- servant-http-streams/servant-http-streams.cabal
- servant-machines/servant-machines.cabal
- servant-pipes/servant-pipes.cabal
- servant-server/servant-server.cabal
- servant/servant.cabal
Tested with 
```
constraints: bytestring >=0.11
allow-newer: *:bytestring
source-repository-package
type: git
location: https://github.com/Bodigrim/hspec-wai
tag: master
```
Since `servant` does not support GHC < 8.0, version bumps are enough.
> Allow bytestring-0.11

- .gitignore
- cabal.project
- doc/cookbook/db-sqlite-simple/db-sqlite-simple.cabal
- servant-docs/test/Servant/DocsSpec.hs
The scope of this PR, as the others that will follow, is to fix servant cookbooks.
This PR make the project compiling and propose a first step through that goal.
Here are the tasks that have been made : 
- Fixing the network bug
- Commenting servant-quickcheck cookbook which is trapped into a dependency loop for now (see [this issue](https://github.com/haskell-servant/servant-quickcheck/issues/74))
- Fixing DocSpec failing test
- Bringing sqlite-simple cookbook back to life
> Fixing Servant cookbooks part 1 (-testing + sqlite-simple)

- doc/cookbook/uverb/UVerb.lhs
- doc/cookbook/uverb/uverb.cabal
As discussed in https://github.com/haskell-servant/servant/issues/1404 some cookbooks will have a minimal version of GHC, higher than 8.0.2.
Here the first PR to fix UVerb cookbook by using `DerivingVia` and `DerivingStrategies` extensions.
@gdeest Would you please add a minimal GHC constraint for this cookbook into the CI checks plan?
> Using DerivingVia in UVerb's cookbook

- cabal.project
- doc/cookbook/https/https.cabal
Related to : https://github.com/haskell-servant/servant/issues/1411
enabling https cookbook
> enabling https cookbook

- cabal.project
- doc/cookbook/hoist-server-with-context/hoist-server-with-context.cabal
Related to https://github.com/haskell-servant/servant/issues/1411
Enabling hoist-server-with-context cookbook
Compability with GHC 8.0.2 has been dropped because `servant-auth-server-0.4.4.0` isn't compatible with it anymore. See : haskell-servant/servant-auth@90d14b4
> enabling hoist-server-with-context cookbook

- servant-docs/golden/comprehensive.md
- servant-docs/src/Servant/Docs/Internal.hs
- servant/src/Servant/Test/ComprehensiveAPI.hs
fixes #1422
When a capture includes a description, e.g. `Capture' '[Description "the id of the Foo to retrieve"] "id" Text]` instead of `Capture "id" Text`, the description is now used in the generated documentation. Previously, the `Description` was ignored and the user had to specify an instance repeating both strings at the value level:
instance ToCapture (Capture "id" Text) where
toCapture _ = DocCapture "id" "the id of the Foo to retrieve"
[The example `ComprehensiveAPI`](https://github.com/haskell-servant/servant/blob/d06b65c4e6116f992debbac2eeeb83eafb960321/servant/src/Servant/Test/ComprehensiveAPI.hs#L51) already uses both `Capture' '[Description "example description"] "foo" Int` and `Capture "foo" Int`, and ./servant-docs/test/Servant/DocsSpec.hs provides a `ToCapture (Capture …
> use Capture Description if available

- servant-client-core/src/Servant/Client/Core/HasClient.hs
- servant-client/test/Servant/ClientTestUtils.hs
- servant-client/test/Servant/SuccessSpec.hs
- servant-server/servant-server.cabal
- servant-server/src/Servant/Server/UVerb.hs
- servant-server/test/Servant/ServerSpec.hs
- servant/src/Servant/API/ResponseHeaders.hs
This implements response header generation for UVerb. It uses an internal `HasResponseHeaders` class with a general overlappable instance.
This should fix #1373.
> Add response header support to UVerb

- servant-client/test/Servant/SuccessSpec.hs
- servant-server/test/Servant/ServerSpec.hs
This is a followup to #1420. It uses `respond` and `matchUnion`, with the help of some type annotations, instead of the NS constructors from SOP.
> Avoid using SOP constructors directly

- servant-http-streams/servant-http-streams.cabal
Master doesn't compile anymore : 
```
lib/Network/Http/Internal.hs:291:13: error:
Error:     • Variable not in scope: (<>) :: Builder -> Builder -> t7
from servant-http-streams-0.18.3 and test:readme from
• Perhaps you meant one of these:
‘<’ (imported from Prelude), ‘<$>’ (imported from Prelude),
servant-http-streams-0.18.3). See the build log above for details.
‘*>’ (imported from Prelude)
|
291 |             <> dashdash
|             ^^
```
add a constraint to http-common to make it build against ghc 8.2.2
> Fix CI by adding a constraint to http-common to make it build against ghc 8.2.2

- cabal.project
- doc/cookbook/uverb/uverb.cabal
- nix/README.md
- nix/shell.nix
> Update to GHC 9 (sub tasks)

- changelog.d/1477
- servant/src/Servant/API/ContentTypes.hs
Starting with GHC 9.2, UndecidableInstances no longer implies FlexibleContexts.
Add this extension where it's needed to make compilation succeed.
> Enable FlexibleContexts in Servant.API.ContentTypes

- servant-server/src/Servant/Server/Internal/ServerError.hs
ServerError field errBody uses ByteString, whose IsString instance kills
Unicode, thus turning example into garbage. Changed it to simple ASCII
string, since Unicode art did not exactly correspond to 404 error
anyway.
Fixes #1371
> Get rid of Unicode in err404 example

- cabal.project
- doc/cookbook/jwt-and-basic-auth/jwt-and-basic-auth.cabal
- servant-auth/servant-auth-client/servant-auth-client.cabal
- servant-auth/servant-auth-server/servant-auth-server.cabal
Turns out the tests broke because of base64-bytestring issue specific to
GHC-9 that was fixed in 1.2.1.0.
Fixes #1473
Fixes #1474
> Fix tests for some servant-auth pkgs on GHC 9

- servant-docs/src/Servant/Docs/Internal.hs
- servant-docs/src/Servant/Docs/Internal/Pretty.hs
I noticed that JSON prettifying works not for all endpoints servant verbs.
So I added missing cases with other verbs aliases to `Pretty` type family :)
> servant-docs: Add support of Pretty modifier for all verbs aliases

- servant-client-core/servant-client-core.cabal
- servant-client-core/src/Servant/Client/Core/HasClient.hs
- servant-client-core/src/Servant/Client/Core/Reexport.hs
- servant-client-core/src/Servant/Client/Generic.hs
- servant-client/servant-client.cabal
- servant-client/test/Servant/ClientTestUtils.hs
- servant-client/test/Servant/GenericSpec.hs
- servant-server/example/greet.hs
- servant-server/servant-server.cabal
- servant-server/src/Servant/Server/Generic.hs
- servant-server/src/Servant/Server/Internal.hs
- servant/servant.cabal
- servant/src/Servant/API.hs
- servant/src/Servant/API/Generic.hs
- servant/src/Servant/API/NamedRoutes.hs
- servant/src/Servant/Links.hs
**Update (2021-11-17):**
The PR has significantly changed since its inception, so here is an updated example for newcomers that may want to see the current state. Users can now mark part of an API as being *directly* defined by a record using the `NamedRoutes` combinator. Here is an example:
```haskell
type Api = NamedRoutes RootApi
data RootApi mode = RootApi
{ subApi :: mode :- Capture "token" String :> NamedRoutes SubApi
, hello :: mode :- Capture "name" String :> Get '[JSON] String
, …
} deriving Generic
data SubApi mode = SubApi
{ endpoint :: mode :- Get '[JSON] Person
, …
} deriving Generic
```
On the surface, it looks exactly the same as what servant's current support for generics provides, just replacing `ToServantApi` by `NamedRoutes`. The nuance here is that `NamedRoutes` is an …
> Improve API for composing generic routes

- servant-client-core/src/Servant/Client/Core/HasClient.hs
- servant-server/src/Servant/Server/Internal.hs
- servant/src/Servant/Links.hs
> Rename proof to g{Client,Server,Link}Proof

- servant/servant.cabal
- servant/src/Servant/API/TypeErrors.hs
- servant/src/Servant/Links.hs
Expressions with partially applied combinators are actually well-typed, even though they do not represent valid endpoints.
Take for instance the following malformed API:
```haskell
> type BadAPI = CaptureAll "path" :> EmptyAPI
```
which is incorrect because `CaptureAll` requires an additional argument (the type of the values to capture). This definition does not produce a type error, but later when trying to use `BadAPI` one gets confusing errors due to non-existing instances:
```haskell
> err :: (Link -> a) -> Proxy BadAPI -> Link -> MkLink BadAPI a
> err = toLink
```
```
* No instance for (HasLink BadAPI) arising from a use of `toLink'
* In the expression: toLink
...
```
The goal is to have more explicative error messages.
This PR proposes custom error messages at the type level. …
> Better errors for partially applied combinators

- .gitignore
- servant/src/Servant/API/ResponseHeaders.hs
This PR describes the behaviour of the two `AddHeader` instances. These comments are implementation-specific and should not be needed by users.
> Add details about AddHeaders instances

- servant-client-core/src/Servant/Client/Core/Request.hs
- servant-client-core/test/Servant/Client/Core/RequestSpec.hs
A parenthesis was misplaced in the manually written `Show` instance of `RequestF` which had the consequence of misplacing the parenthesis if the `RequestF` was embedded in another type.
Here is the test failure with the original code:
```
expected: "DataWithRequest (Request {requestPath = (), requestQueryString = fromList [], requestBody = Nothing, requestAccept = fromList [], requestHeaders = fromList [], requestHttpVersion = HTTP/1.1, requestMethod = \"GET\"})"
but got: "DataWithRequest (Request {requestPath = (), requestQueryString = fromList [], requestBody = Nothing, requestAccept = fromList [], requestHeaders = fromList []), requestHttpVersion = HTTP/1.1, requestMethod = \"GET\"}"
```
Notice how the `)` got moved from the finish to after `requestHeaders`.
> Fix Request's Show instance

- changelog.d/1469
- servant-client-core/src/Servant/Client/Core/HasClient.hs
- servant-client/servant-client.cabal
- servant-client/src/Servant/Client/Internal/HttpClient.hs
- servant-client/src/Servant/Client/Internal/HttpClient/Streaming.hs
- servant-client/test/Servant/BrokenSpec.hs
- servant-client/test/Servant/ClientTestUtils.hs
- servant-client/test/Servant/FailSpec.hs
- servant-client/test/Servant/SuccessSpec.hs
- servant-http-streams/src/Servant/HttpStreams/Internal.hs
- servant-server/src/Servant/Server/Internal.hs
- servant/src/Servant/API/Status.hs
Hi Everyone,
There's a limitation/bug in the `HasClient` instances for the `Verb` datatype.
If I try to perform a client request with `runClientM`, I'll obtain a successful response if and only if the backend endpoint returns a response with status code >=200 and <300. This is due to the use of `runRequest` in the `clientWithRoute` definitions.
This PR brings the following changes:
- Replace `runRequest` with `runRequestAcceptStatus` in the `Verb` instances for the `HasClient` class (as suggested by @alpmestan).
- Derive the good response status from the `Verb` status.
- Use `statusIsSuccessful` from `Network.HTTP.Types.Status` to lighten the code (not required to solve the issue).
> Derive HasClient good response status from Verb status

- servant/src/Servant/API/Verbs.hs
As the head method isn't allowed to contain any response body, no
general Head Verb is added. (This may easily lead to wrong usages...)
(https://httpwg.org/specs/rfc7231.html#HEAD)
> Add HeadNoContent to Servant.API.Verbs

- servant-client-core/src/Servant/Client/Core/HasClient.hs
- servant-server/src/Servant/Server/Internal.hs
This PR applies the approach from #1289 to `HasServer` and `HasClient`.
The `context` parameter is missing from the missing instance message in one case, but I am not sure it is a big enough problem to warrant making the code more complex.
In the process, I realized there was already a similar mechanism in place to detect usage errors for `HasServer`. The mechanism #1289 supersedes it, as it produces more informative messages, displays the number of missing parameters, etc.
> Custom errors for HasClient, HasServer

- servant/src/Servant/Links.hs
Close #1513.
GHC 9.2 needs explicit kind signature here, I don't really understand
why.
This kind signature is correct and not too restritive, because `HasLink`
is technically defined `class HasLink endpoint` which means that it is
infered as `k -> Constraint`. In the instance signature, we have
`HasLink ((arr :: a -> b) :> sub)`, so here the `k` is the same kind as
the one of `:>` which is not polykinded.
Note: build tested with GHC 9.2 and the following workflow:
```
$ nix-shell ./ --argstr compiler 'ghc921' --arg pkgs 'import <nixpkgs> {}' -A servant
[nix-shell:~/srcs/servant]$ nix-shell -p cabal-install
[nix-shell:~/srcs/servant]$ cabal build servant
Up to date
```
I had to bump a few bounds:
```diff
diff --git a/cabal.project b/cabal.project
index ac4a4e3b..e2573fa9 100644
--- …
```
> Fix GHC 9.2 build

- servant/CHANGELOG.md
There are small errors in the example showcasing 0.19's NamedRoutes
> Fix NamedRoutes example in 0.19 changelog

- CONTRIBUTING.md
- doc/cookbook/index.rst
- doc/links.rst
Looks like `#servant` is now hosted on libera.
> Update docs: #servant is now on libera.chat

- servant-server/src/Servant/Server/Internal.hs
The issue is similar to the one in #1513:
```
src/Servant/Server/Internal.hs:824:10: error:
• Uninferrable type variable k0 in
type family equation right-hand side: (TypeError ...)
• In the type instance declaration for ‘ServerT’
In the instance declaration for
‘HasServer ((arr :: a -> b) :> sub) context’
|
824 |     type ServerT (arr :> sub) _ = TypeError (PartialApplication HasServer arr)
|
```
This fix is similar to the one in #1514.
> servant-server: Fix build on GHC 9.2.1

- servant-auth/servant-auth-server/src/Servant/Auth/Server/Internal/AddSetCookie.hs
- servant-auth/servant-auth-server/src/Servant/Auth/Server/Internal/ThrowAll.hs
- servant-auth/servant-auth-server/test/Servant/Auth/ServerSpec.hs
Trying to use `NamedRoutes` with `servant-auth-server` currently results
in hideous error messages such as:
```
app/Main.hs:50:7: error:
• No instance for (Servant.Auth.Server.Internal.AddSetCookie.AddSetCookies
('Servant.Auth.Server.Internal.AddSetCookie.S
('Servant.Auth.Server.Internal.AddSetCookie.S
'Servant.Auth.Server.Internal.AddSetCookie.Z))
(AdminRoutes (Servant.Server.Internal.AsServerT Handler))
(ServerT
(Servant.Auth.Server.Internal.AddSetCookie.AddSetCookieApi
(Servant.Auth.Server.Internal.AddSetCookie.AddSetCookieApi
(NamedRoutes AdminRoutes)))
Handler))
arising from a use of 'serveWithContext'
• In the expression: serveWithContext (Proxy @API) ctx RootAPI {..}
```
This is because we didn't teach it how to recurse along `NamedRoutes`
trees and sprinkle headers at the tip of …
> servant-auth-server: Support NamedRoutes

- changelog.d/1529
- servant-client-ghcjs/servant-client-ghcjs.cabal
- servant-client-ghcjs/src/Servant/Client/Internal/XhrClient.hs
I fixed servant-client-ghcjs to be compatible with servant-client-core version 0.19, also bumped max-bound on base to be able to use base 4.14
> Fix servant-client-ghcjs for servant 0.19

- cabal.project
Removing these bounds adjustments doesn't seem to impede building for any GHC version. The
disadvantage of them is that they make people not notice when bounds need
updating, which will make each project just replicate the same allow-newer
list. Better remove them when unnecessary such that a potential future upstream issue can be
found.
> Remove unnecessary constraint/allow-newer

- servant-client-core/src/Servant/Client/Core.hs
- servant-client-core/src/Servant/Client/Core/HasClient.hs
- servant-client-core/src/Servant/Client/Core/Request.hs
After the refactoring of URL encoding (https://github.com/haskell-servant/servant/pull/1432), the type of the `appendToQueryString` function has changed.
It might be helpful to export the function `encodeQueryParamValue` (it was `encodeQueryParam`) that could be used to obtain the proper value to pass to `appendToQueryString`, when this function is used outside of `servant`.
This PR proposes to:
- move `encodeQueryParam` from `Servant.Client.Core.HasClient` to `Servant.Client.Core.Request`
- rename `encodeQueryParam` into `encodeQueryParamValue`, just to be more explicit
- re-export `encodeQueryParamValue` from `Servant.Client.Core`
- add short descriptions to some of the exported functions of the `Servant.Client.Core.Request` module
> Export encoding function for a query parameter value

- .github/workflows/master.yml
- cabal.project
- servant-client/src/Servant/Client/Internal/HttpClient.hs
- servant-swagger/servant-swagger.cabal
Doctests can be made more robust by making cabal-install invoke doctest with the right configuration. This is a new feature added in doctest 0.20. This makes the environment files unnecessary, and the CI configuration becomes simpler.
This also inserts a space such that `$requestHeaders` isn't mistaken for a TemplateHaskell splice.
> Use cabal-install to invoke doctest

- servant-client-core/src/Servant/Client/Core/HasClient.hs
The examples for these two operators weren't displayed properly due to invalid Haddock markup (see [here](https://hackage.haskell.org/package/servant-client-core-0.19/docs/Servant-Client-Core-Reexport.html#v:-47-:) for example).
> Fix haddock documentation for (//) and (/:)

- .github/workflows/master.yml
- cabal.project
servant-pagination 2.5.0 is out, and it allows servant 0.19. So we do not need this allow-newer any more. Stack 2.7.5 is out, and it only downloads extra-deps with multiple subdirs once, and also contains other bugfixes. A stale CI configuration line is removed, since GHC 9.0.1 is no longer run in CI, we use GHC 9.0.2.
> Use Stack 2.7.5, cleanup allow-newer/CI

- changelog.d/1569
- servant-client-core/src/Servant/Client/Core/HasClient.hs
- servant-client-core/src/Servant/Client/Core/Request.hs
- servant-client/test/Servant/ClientTestUtils.hs
- servant-client/test/Servant/SuccessSpec.hs
Current implementation of captures uses the `toUrlPiece` method from the
`ToHttpApiData` typeclass, and encodes the resulting `Text` using `toEncodedUrlPiece`
when appending to the request path.
The problem with this approach is that the instance for `Text` percent-encodes
characters that are perfectly valid in URLs, such as `*`.
This patch makes direct use of `toEncodedUrlPiece`, which lets users implement
encoding according to their needs.
Closes #1511
> Use toEncodedUrlPiece directly when encoding captures

- changelog.d/1556
- servant-server/src/Servant/Server.hs
- servant-server/src/Servant/Server/Internal.hs
- servant-server/src/Servant/Server/Internal/Router.hs
- servant-server/test/Servant/Server/RouterSpec.hs
This PR introduces a `CaptureHint` type, which is passed as an extra argument to the `CaptureRouter` and `CaptureAllRouter` constructors for the `Router'` type.
`CaptureHint` values are then used in `routerLayout`, to display the name and type of captured values, instead of just `<capture>` previously.
N.B.:
Because the `choice` smart constructor for routers can aggregate `Capture` combinators with different capture hints, the `Capture*Router` constructors actually take a *list* of `CaptureHint`, instead of a single one.
This PR also introduces `Spec` tests for the `routerLayout` function.
**Warning:**
This change is potentially breaking, because it adds the constraint `Typeable a` to all types that are to be captured. Because all types are typeable since GHC 7.10, this is not as bad as …
> Display capture hints in router layout

- servant-server/servant-server.cabal
I made the revision on hackage, just reflecting it here.
> Major version bound for servant-server's dependency on servant

- servant-swagger/src/Servant/Swagger.hs
- servant-swagger/src/Servant/Swagger/Internal/Test.hs
Colored output is the default since hspec 2.9.5.
> **Changes in 2.9.5**
>
>    Assume --color by default when running on GitHub Actions. Use HSPEC_COLOR=no or --no-color to opt out of this behavior.
This causes CI failures due to terminal escaping characters when running
the doctests on GitHub Actions.
> Disable hspec colored output in servant-swagger doctests

- changelog.d/1580
- servant-auth/servant-auth-server/src/Servant/Auth/Server/Internal/ConfigTypes.hs
- servant-auth/servant-auth-server/src/Servant/Auth/Server/Internal/JWT.hs
Fixes #1579 
There have been two PRs in the old servant-auth repo doing similar things. [This one](https://github.com/haskell-servant/servant-auth/pull/193/files) by [dnikolovv](https://github.com/dnikolovv) which uses IORefs, and [this one](https://github.com/haskell-servant/servant-auth/pull/169/files) by me which allows IO as here (but that PR also does a lot of other things).
I personally prefer `IO` rather than `IORef` since it's a bit more general (and works with libraries that either don't use or don't expose the `IORef` - e.g. [cached-io](https://hackage.haskell.org/package/cached-io)).
This is a breaking change.
> Allow IO in JWTSettings' validationKeys

- servant/src/Servant/API/ContentTypes.hs
- servant/test/Servant/API/ContentTypesSpec.hs
This way it shows up as covered in coverage reports,
Currently any `return NoContent` is marked at "not covered" in coverage reports because it is not evaluated.
> Evaluate NoContent before (not) rendering it.

- servant-swagger/src/Servant/Swagger/Internal.hs
I need an instance like this to generate API docs for my API that uses NamedRoutes.
I'm using the API record type name to tag the contained endpoints, so that they appear grouped in the Swagger UI. I'm open to changing this.
> Add HasSwagger instance for NamedRoutes

- changelog.d/1595
- doc/cookbook/using-free-client/UsingFreeClient.lhs
- servant-client/src/Servant/Client/Internal/HttpClient.hs
- servant-client/src/Servant/Client/Internal/HttpClient/Streaming.hs
- servant-client/test/Servant/SuccessSpec.hs
Use cases:
- [applyDigestAuth](https://hackage.haskell.org/package/http-client-tls-0.3.6.1/docs/Network-HTTP-Client-TLS.html#v:applyDigestAuth)
- Sign requests
> servant-client: Run ClientEnv's makeClientRequest in IO

- cabal.project
Upstream has released updated versions.
> Remove allow-newer for postgresql-simple

- changelog.d/1606
- servant-client/src/Servant/Client/Internal/HttpClient/Streaming.hs
Makes `performWithStreamingRequest` take into consideration the
CookieJar, which it previously didn't.
It's now possible to e.g. use the servant-client generated functions to
access a streaming endpoint that depends on a cookie being set to
authenticate the user
Fixes #1605
> Handle Cookies correctly for RunStreamingClient

- servant/src/Servant/API/UVerb/Union.hs
The `Elem` call was not possible to resolve with polymophic type. For example, the following `forall a. Elem (Maybe a) '[Maybe a, Int]` cannot be resolved.
I don't really understand the reasons why, looks like the former implementation with `If (a == b)` does not work with polymophic types.
The new implementation uses pattern matching in closed type families.
Close #1590 and #1381.
> feat: Polymorphic `Elem` for `Union`

- doc/cookbook/open-id-connect/OpenIdConnect.lhs
- doc/cookbook/uverb/UVerb.lhs
- servant-auth/servant-auth/src/Servant/Auth.hs
- servant-client-core/src/Servant/Client/Core/HasClient.hs
- servant-docs/src/Servant/Docs/Internal.hs
The code examples don't render properly, because '/' needs to be escaped when used in `@...@` code blocks.
> Fix haddock code examples in HasClient

- servant-server/servant-server.cabal
`Network.Wai.getRequestBodyChunk` is not available earlier than `wai-3.2.2.1`.
As a Hackage trustee I revised `servant-server-0.19.{1,2}`.
> Require wai >= 3.2.2.1

- changelog.d/1571
- servant-auth/servant-auth-server/servant-auth-server.cabal
- servant-auth/servant-auth-server/src/Servant/Auth/Server/Internal.hs
- servant-auth/servant-auth-server/src/Servant/Auth/Server/Internal/AddSetCookie.hs
- servant-auth/servant-auth-server/test/Servant/Auth/ServerSpec.hs
- servant/src/Servant/API/ResponseHeaders.hs
- servant/src/Servant/API/UVerb.hs
Closes #1570 
~Caveat: returning a 401 response with UVerb is _not_ equivalent to using `throwAll err401`: `XSRF-TOKEN` will be set anyway, because the handler then doesn't fail (it successfully returns an error :upside_down_face:). I can't see a satisfying solution to this problem, so external input is much welcome on this issue (I for one consider this limitation semi-reasonable).~ This should be fixed.
> Support UVerb in servant-auth-server

- servant-client-core/src/Servant/Client/Core/HasClient.hs
- servant-server/src/Servant/Server/Internal.hs
- servant-server/test/Servant/ServerSpec.hs
- servant/src/Servant/API.hs
- servant/src/Servant/API/Raw.hs
- servant/src/Servant/Links.hs
The 'RawM' combinator is a variant of 'Raw' that lets users access the monadic context of the server.
The handler must produce a WAI Response, like Raw.
Closes #1544 .
@hasufell may I have your input on this PR ?
> Add RawM combinator

- servant-auth/servant-auth-server/src/Servant/Auth/Server/Internal/Cookie.hs
It is currently missing, which causes a [warning](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#cookies_without_samesite_default_to_samesitelax) in modern browsers.
By moving it to `applyCookieSettings`, the value specified in `cookieSameSite` is used for both the session cookie and the XSRF token cookie.
> Add SameSite attribute to XSRF token cookie

- servant-client-ghcjs/servant-client-ghcjs.cabal
- servant-client/servant-client.cabal
- servant-http-streams/servant-http-streams.cabal
Relaxes bounds on `semigroupoids` for `servant-client` and `servant-http-streams`
> Allow semigroupoids < 6.1

- changelog.d/1665
- servant-client/test/Servant/ClientTestUtils.hs
- servant-client/test/Servant/SuccessSpec.hs
- servant/src/Servant/API/ResponseHeaders.hs
Fix recursion in the instance `BuildHeadersTo (Header h v ': xs)` so that multiple headers with the same name work in `servant-client`.
Fixes #1665
> Fix multiple headers with the same name

- servant/src/Servant/API/UVerb/Union.hs
The comment says `CheckElemIsMember` can throw error which it cannot actually throw.
But that error can be thrown by *another* type family in this module - `Unique`
> Fix haddocks for type families in Servant.API.UVerb.Union

- changelog.d/1593
- servant/src/Servant/Types/SourceT.hs
I didn't see any reason to restrict this function to only work on lists, so I changed the type signature from
```haskell
source :: [a] -> SourceT m a
```
to
```haskell
source :: Foldable f => f a -> SourceT m a
```
> [servant] Generalize type of Servant.Types.SourceT.source to any foldable

- changelog.d/1646
- servant/src/Servant/API/ContentTypes.hs
Commit message: change `Mime(Un)Render PlainText String` instances to encode/decode UTF-8 data as specified by `Accept PlainText` instance
Details: https://github.com/haskell-servant/servant/issues/1645
> change `Mime(Un)Render PlainText String` instances to encode/decode UTF-8

- servant-client-core/src/Servant/Client/Core/Request.hs
closes #1584
I was investigating a bug in our application and it turned out it was caused by servant-client not escaping plus signs in query params. After some digging down the code in servant-client I noticed servant-client uses `toEncodedUrlPiece` to encode the values of QueryParams, which is wrong because it should be used for path pieces only and it does not escape characters `:@&=+$,`. Later I found https://github.com/haskell-servant/servant/issues/1584 and https://github.com/haskell-servant/servant/pull/1586. Here I'm suggesting a workaround — using `urlEncodeBuilder True` directly instead of `toEncodedUrlPiece`.
At first I thought the `toEncodedUrlPiece` is itself the source of the problem and created a PR to https://github.com/fizruk/http-api-data/pull/119. The conclusion there …
> Escape special chars in QueryParams

- cabal.project
The crypton fork of cryptonite seems to have broken its use in servant (CI for master is currently broken). So for now, let's avoid crypton. Since this is in `cabal.project`, it won't affect users of the libraries, only developers.
* https://github.com/yesodweb/wai/issues/932
* https://github.com/yesodweb/wai/issues/934
* https://github.com/snoyberg/http-client/issues/508
> Avoid crypton dependency for now

- changelog.d/1661
- servant-client-core/src/Servant/Client/Core/HasClient.hs
- servant-conduit/src/Servant/Conduit.hs
- servant-machines/src/Servant/Machines.hs
- servant-pipes/src/Servant/Pipes.hs
- servant-server/src/Servant/Server/Internal.hs
- servant/src/Servant/API/Stream.hs
Needed for stateful initialization like io-streams.
> fromSourceIO: Run in IO.

- servant-auth/servant-auth-client/servant-auth-client.cabal
- servant-auth/servant-auth-docs/servant-auth-docs.cabal
- servant-auth/servant-auth-server/servant-auth-server.cabal
- servant-auth/servant-auth-swagger/servant-auth-swagger.cabal
- servant-auth/servant-auth/servant-auth.cabal
- servant-client-core/servant-client-core.cabal
- servant-client-ghcjs/servant-client-ghcjs.cabal
- servant-client/servant-client.cabal
- servant-foreign/servant-foreign.cabal
- servant-http-streams/servant-http-streams.cabal
- servant-server/servant-server.cabal
- servant-swagger/servant-swagger.cabal
- servant/servant.cabal
Especially the free bound is important for inclusion into Stackage Nightly.
I have also bumped the min bound for servant-auth, since jose-0.10 requires aeson-2, we might as well.
Also included is a bump for monad-time.
> Allow newer hspec, free

- servant-server/servant-server.cabal
- servant/servant.cabal
Fixes #1691. When all dependencies for all packages support aeson-2.2, we should adjust our code to be compatible.
> Adjust bounds for http-api-data and aeson

- servant-auth/servant-auth-client/test/Servant/Auth/ClientSpec.hs
- servant-auth/servant-auth-server/test/Servant/Auth/ServerSpec.hs
use `aroundAll` instead of `around` with `testWithApplication`, to avoid allocating a new port for every example of a QuickCheck property we're testing (and exhausting the per-process file descriptor limit on Macs)
Fixes #1693
> use `aroundAll` instead of `around` with `testWithApplication`

- CONTRIBUTING.md
This PR updates the commands mentioned in CONTRIBUTING.md. It removes the no longer existing scripts in favor of up-to-date Cabal / Stack / Nix commands.
Should fix #1027.
This PR also uses consistent longer lines in the file, but it might be less desirable. The associated commit can be removed if it is.
> Documentation: Update commands in CONTRIBUTING.md

- cabal.ghcjs.project
See test failure on main branch.
> Avoid clock-0.8.4 which breaks ghcjs

- changelog.d/full-header-type
- servant-auth/servant-auth-server/src/Servant/Auth/Server/Internal/AddSetCookie.hs
- servant-auth/servant-auth-server/src/Servant/Auth/Server/Internal/Cookie.hs
- servant-server/test/Servant/ServerSpec.hs
- servant-swagger/src/Servant/Swagger/Internal.hs
- servant/src/Servant/API.hs
- servant/src/Servant/API/ResponseHeaders.hs
- servant/src/Servant/API/TypeLevel.hs
- servant/test/Servant/API/ResponseHeadersSpec.hs
- stack.yaml
This is required to be able provide `Description` into headers, for example like this:
```
type PaginationTotalCountHeader =
Header'
'[ Description "Indicates to the client total count of items in collection"
, Optional
, Strict
]
"Total-Count"
Int
```
This PR is related to another one: https://github.com/biocad/servant-openapi3/pull/48 and related to issue https://github.com/biocad/servant-openapi3/issues/45
> Use full header type in response header instances

- cabal.project
- changelog.d/1699
- servant/src/Servant/API/TypeLevel.hs
- servant/test/Servant/LinksSpec.hs
Added various tests for NamedRoutes too.
In writing the tests I realised that the client combinators `//` and `/:` can be used to create links in the same natural way.
I've added the combinators to the test suite for now, but it probably makes sense to put them somewhere in the `servant` package, though I wasn't sure where. Maybe just in the root `API` module, and then ensure that `HasClient` and `Reexport` in `servant-client-core` reexport them for any backwards compatibility?
Fixes #1674.
> Add missing IsElem instance for NamedRoutes

- servant-client-core/src/Servant/Client/Core/RunClient.hs
- servant-client-core/src/Servant/Client/Generic.hs
- servant-conduit/src/Servant/Conduit.hs
- servant-pipes/src/Servant/Pipes.hs
- servant/src/Servant/Types/SourceT.hs
See #1681. Adds `LANGUAGE TypeOperators` where warned that this will be needed, such as:
```
$ cabal build all --enable-tests --enable-benchmarks
Resolving dependencies...
Build profile: -w ghc-9.4.7 -O0
...
src/Servant/Types/SourceT.hs:73:19: warning: [-Wtype-equality-requires-operators]
The use of ‘~’ without TypeOperators
will become an error in a future GHC release.
Suggested fix: Perhaps you intended to use TypeOperators
|
73 | instance Identity ~ m => Foldable (SourceT m) where
|  
```
Can be tested by doing a rebuild from clean with this warning as an error:
```diff
$ git diff
diff --git a/cabal.project b/cabal.project
index 2239b77c..888f4689 100644
--- a/cabal.project
+++ b/cabal.project
@@ -77,3 +77,6 @@ if(impl(ghc >= 9.6.1))
allow-newer: servant-multipart:servant, …
```
> Add -XTypeOperators

- cabal.project
These revisions were just made today, so we should no longer need this.
> Remove unnecessary servant-multipart{,-api} allow-newers

- servant-conduit/example/Main.hs
> Fix typo in servant-conduit example

- servant-swagger/src/Servant/Swagger/Internal/TypeLevel/API.hs
- servant/src/Servant/API/TypeLevel.hs
This was needed for adding custom tags using the [subOperations](https://hackage.haskell.org/package/servant-swagger-1.2/docs/Servant-Swagger.html#v:subOperations) combinator. `IsSubAPI` constraint could not resolve for APIs using the new `NamedRoutes`.
> Add `IsIn` instance for `NamedRoutes`

- .github/workflows/master.yml
- servant-client-core/servant-client-core.cabal
- servant-client-ghcjs/servant-client-ghcjs.cabal
- servant-client/servant-client.cabal
- servant-conduit/servant-conduit.cabal
- servant-docs/servant-docs.cabal
- servant-foreign/servant-foreign.cabal
- servant-http-streams/servant-http-streams.cabal
- servant-machines/servant-machines.cabal
- servant-pipes/servant-pipes.cabal
- servant-server/servant-server.cabal
- servant-swagger/servant-swagger.cabal
- servant/servant.cabal
In order to minimise drift, CI testing matrix can be derived from the `tested-with` stanza of the cabal file, which in turn is also displayed by [Flora.pm](https://flora.pm/packages/@hackage/servant)
> Use tested-with for CI

- changelog.d/1604
- servant-client-core/src/Servant/Client/Core/HasClient.hs
- servant-client-core/src/Servant/Client/Core/Request.hs
- servant-client/test/Servant/ClientTestUtils.hs
- servant-client/test/Servant/SuccessSpec.hs
- servant-server/src/Servant/Server/Internal.hs
- servant-server/test/Servant/ServerSpec.hs
- servant/servant.cabal
- servant/src/Servant/API.hs
- servant/src/Servant/API/QueryString.hs
The goal of this PR is to adress a use-case that is not currently covered by servant: query strings with dynamic parameter names.
`QueryParam` and its friends are super useful, but extract the parameter name from a type-level string, so while this is useful in many cases, it cannot cover every use-case. A typical use-case would be implementing a search filter where filters are not static and can't be enumerated ahead of time.
I'll propose two helpers, directly derived from a use case that came up at work:
- one is an escape hatch that extracts the whole query string as a `[(ByteString, Maybe ByteString)]` value. It cannot fail and provides raw access to the query string: `QueryString :> Get '[JSON] [Book]`.  
This was the first version that i implemented for my concrete use-case at work, …
> Full query string helpers

- servant-client/servant-client.cabal
- servant-http-streams/servant-http-streams.cabal
- servant-quickcheck/doc/doc.cabal
- servant-quickcheck/doc/posts/posts.cabal
- servant-quickcheck/servant-quickcheck.cabal
- servant-server/servant-server.cabal
Tested with
cabal build -c 'network>=3.2' -c 'filepath >= 1.4' -c 'warm >= 3.4' --allow-newer=swagger2:network,io-streams:network,openssl-streams:network,HsOpenSSL:network
I have created issues for these allow-newers. Have removed version constraints from cookbook examples since we always forget them. And they're not published anyway.
> Accept network-3.2, misc bumps

- changelog.d/1733
- servant-server/src/Servant/Server.hs
- servant-server/src/Servant/Server/Internal/Handler.hs
This bidirectional pattern synonym makes it easier to build `Handler a` values from `IO (Either ServerError a)` values, and is a complement to the already existing `runHandler` function.
As an alternative to this, I also considered re-exporting the `ExceptT` constructor, but I think it's better to have an explicit pattern synonym. `ExceptT` is not exactly an internal implementation detail, but it's sufficiently close to being one.
As for naming the pattern synonym, I considered `HandlerT` but it would be a bit misleading because `Handler` is not really a monad transformer. The prefix is `Mk` instead of `Make` because other parts of the Servant ecosystem (like safe links) have already settled on `Mk`.
Solves #1732.
> Add `MkHandler` pattern synonym

- servant/servant.cabal
- servant/src/Servant/API/Alternative.hs
- servant/src/Servant/API/ContentTypes.hs
- servant/src/Servant/API/Empty.hs
- servant/src/Servant/API/ResponseHeaders.hs
- servant/src/Servant/Links.hs
- servant/src/Servant/Types/SourceT.hs
First batch of removing extraneous dependencies.
> Remove base-compat dependency from servant

- doc/tutorial/Docs.lhs
- servant-docs/example/greet.md
- servant-docs/golden/comprehensive.md
- servant-docs/src/Servant/Docs/Internal.hs
This PR fixes servant-docs: Wrong markdowntype javascript for json
https://github.com/haskell-servant/servant/issues/1358
> fix wrong markdowntype javascript for json

- servant-client-core/servant-client-core.cabal
- servant-client/test/Servant/StreamSpec.hs
- servant-client/test/Servant/SuccessSpec.hs
- servant-docs/golden/comprehensive.md
- servant-quickcheck/servant-quickcheck.cabal
- servant-quickcheck/src/Servant/QuickCheck/Internal/ErrorTypes.hs
- servant-quickcheck/src/Servant/QuickCheck/Internal/HasGenRequest.hs
- servant-server/servant-server.cabal
- servant-server/src/Servant/Server/Internal.hs
- servant-server/src/Servant/Server/Internal/ErrorFormatter.hs
- servant-server/src/Servant/Server/Internal/Handler.hs
- servant-server/src/Servant/Server/Internal/Router.hs
- servant-server/src/Servant/Server/Internal/RoutingApplication.hs
- servant-server/src/Servant/Server/UVerb.hs
- servant-server/test/Servant/Server/ErrorSpec.hs
- servant-server/test/Servant/ServerSpec.hs
- servant/servant.cabal
- servant/src/Servant/API/ContentTypes.hs
- servant/test/Servant/API/ContentTypesSpec.hs
This PR removes unused dependencies, as well as `string-conversions`, which obfuscates the target and destination type of string used.
Due to GHCJS 8.6's inability to have `bytestring`'s `toStrict` function, this PR depends on https://github.com/haskell-servant/servant/pull/1746.
> Remove extraneous dependencies (part 2)

- cabal.project
- servant-client-core/servant-client-core.cabal
- servant-client-core/src/Servant/Client/Core/Auth.hs
- servant-client-core/src/Servant/Client/Core/BaseUrl.hs
- servant-client-core/src/Servant/Client/Core/HasClient.hs
- servant-client-core/src/Servant/Client/Core/Request.hs
- servant-client/servant-client.cabal
- servant-client/src/Servant/Client/Internal/HttpClient.hs
- servant-client/src/Servant/Client/Internal/HttpClient/Streaming.hs
- servant-client/test/Servant/WrappedApiSpec.hs
- servant-docs/example/greet.hs
- servant-server/example/greet.hs
- servant-server/servant-server.cabal
- servant-server/src/Servant/Server/Internal.hs
- servant-server/src/Servant/Server/Internal/DelayedIO.hs
- servant-server/src/Servant/Server/Internal/Handler.hs
- servant-server/src/Servant/Server/Internal/RouteResult.hs
- servant-server/test/Servant/Server/StreamingSpec.hs
- servant-server/test/Servant/Server/UsingContextSpec/TestCombinators.hs
- servant-server/test/Servant/ServerSpec.hs
- servant/servant.cabal
- servant/src/Servant/API/Alternative.hs
- servant/src/Servant/API/Generic.hs
- servant/src/Servant/API/Modifiers.hs
- servant/src/Servant/API/ResponseHeaders.hs
- servant/src/Servant/Links.hs
- servant/src/Servant/Types/SourceT.hs
- servant/test/Servant/API/ContentTypesSpec.hs
This PR adds more compilation flags by default to prevent anti-patterns like non-canonical instances, unrestricted imports of Data.List, redundant imports, etc.
> codebase clean-up

- servant-client-core/servant-client-core.cabal
- servant-client-core/src/Servant/Client/Core/HasClient.hs
- servant-client/servant-client.cabal
- servant-client/src/Servant/Client/Internal/HttpClient.hs
- servant-docs/servant-docs.cabal
- servant-foreign/servant-foreign.cabal
- servant-http-streams/servant-http-streams.cabal
- servant-quickcheck/servant-quickcheck.cabal
- servant-swagger/servant-swagger.cabal
Tested using
cabal build all -c 'base-compat>=0.14'  --allow-newer=servant-openapi3:base-compat,openapi3:base-compat-batteries,swagger2:base-compat-batteries,servant-js:base-compat
> Allow base-compat-0.14

- servant-client-core/src/Servant/Client/Core/HasClient.hs
- servant-client/src/Servant/Client/Internal/HttpClient.hs
- servant-quickcheck/LICENSE
- servant-quickcheck/servant-quickcheck.cabal
This PR prepares the release of servant-quickcheck-0.1.0.0:
* Add missing LICENSE file to servant-quickcheck
closes #1757 
blocks https://github.com/commercialhaskell/stackage/issues/7391
> Prepare servant-quickcheck-0.1.0.0

- servant-auth/servant-auth-client/servant-auth-client.cabal
- servant-auth/servant-auth-docs/servant-auth-docs.cabal
- servant-auth/servant-auth-server/servant-auth-server.cabal
- servant-auth/servant-auth-swagger/servant-auth-swagger.cabal
- servant-client-core/servant-client-core.cabal
- servant-client/servant-client.cabal
- servant-http-streams/servant-http-streams.cabal
- servant/servant.cabal
Tested using
cabal build all -w ghc-9.8.2 -c 'QuickCheck>=2.15' --allow-newer=openapi3:QuickCheck,swagger2:QuickCheck
> Allow QuickCheck-2.15

- cabal.project
The package that wasn't compatible with the newest release was servant-swagger-ui{,-core}, and they were just updated on Hackage.
> Remove allow-newer for file-embed-lzma

- cabal.project
- servant-docs/servant-docs.cabal
Tested using
cabal test servant-docs -w ghc-9.8.2 -c 'tasty>=1.5' -c 'hashable>=1.5'
> Allow hashable-1.5, with allow-newers

- changelog.d/config
- changelog.d/issue-1780
- servant-server/servant-server.cabal
- servant/servant.cabal
This has triggered a regression in 0.20.2, and is related to #1780
> Remove strict data from servant{,-server}'s cabal files

- servant-client/src/Servant/Client/Internal/HttpClient.hs
The `IO` wrap for the return type of this function was never necessary. Inside the function there’s only `return` call that wraps a _pure_ value into `IO`. There is nothing else that would be related to `IO`. The `IO` wrap was introduced in 9df16f9f1a81b0b9ae605820a4348627b102c75d
In order to not break the API again the wrap was preserved but this change makes it to depend on any `Applicative` instead of `IO`. So it still works in `IO`/`MonadIO` context but allows to use something like `Data.Functor.Identity` to work with _pure_ values.
See for more context:
https://github.com/haskell-servant/servant/pull/1595
> Make defaultMakeClientRequest not depend on IO

- servant/src/Servant/API/ContentTypes.hs
It seems that the Content-Type header for `Plaintext` should be `text/plain;charset=utf8` and not `text/plain;charset-utf8`, as I'm getting `415 Unsupported Media Type` for the former.
> Fix typo in Content-Type docs

- servant/src/Servant/API/MultiVerb.hs
This PR adds more instances to ease the transition from UVerb to MultiVerb, and expands on the documentation of `AsHeaders`.
> Add more multiverb

- changelog.d/pr-1800
- servant-client-core/src/Servant/Client/Core/HasClient.hs
- servant-client/test/Servant/ClientTestUtils.hs
- servant-server/src/Servant/Server/Internal.hs
- servant/servant.cabal
- servant/src/Servant/API.hs
- servant/src/Servant/API/Host.hs
This combinator allows you to select or restrict APIs according to the provided hosts. For example:
```haskell
type API = Host "api1.example" :> API1
:<|> Host "api2.example" :> API2
```
I implemented it as far as it was needed to make it work, i.e. adding `HasClient` and `HasServer` instances. If you want me to add support in more places, let me know.
> Add `Host` API combinator

- cabal.project
- default.nix
- flake.lock
- flake.nix
- nix/README.md
- nix/nixpkgs.json
- nix/nixpkgs.nix
- nix/shell.nix
The provided `shell.nix` had an earlier default GHC than the minimum `base` package required to build `servant`. I've updated to use `ghc92` and added a flake.
> fix: update nix shell to work with current bounds, add flake

- changelog.d/1706
- servant-docs/src/Servant/Docs.hs
Add missing `renderCurlBasePath` lens re-export.
A workaround is to use:
```Haskell
import Servant.Docs.Internal qualified as SD (renderCurlBasePath)
```
> [servant-docs] Export renderCurlBasePath lens

- .github/workflows/master.yml
- cabal.project
- doc/cookbook/custom-errors/CustomErrors.lhs
- doc/cookbook/named-routes/cookbook-named-routes.cabal
- doc/tutorial/tutorial.cabal
- servant-auth/servant-auth-client/servant-auth-client.cabal
- servant-auth/servant-auth-docs/servant-auth-docs.cabal
- servant-auth/servant-auth-server/servant-auth-server.cabal
- servant-auth/servant-auth-swagger/servant-auth-swagger.cabal
- servant-auth/servant-auth/servant-auth.cabal
- servant-client-core/servant-client-core.cabal
- servant-client/README.md
- servant-client/servant-client.cabal
- servant-conduit/servant-conduit.cabal
- servant-docs/servant-docs.cabal
- servant-foreign/servant-foreign.cabal
- servant-http-streams/README.md
- servant-http-streams/servant-http-streams.cabal
- servant-machines/servant-machines.cabal
- servant-pipes/servant-pipes.cabal
- servant-quickcheck/servant-quickcheck.cabal
- servant-server/servant-server.cabal
- servant-swagger/servant-swagger.cabal
- servant/servant.cabal
Passed all test locally with `ghc-9.6`, `ghc-9.10` and `ghc-9.12`.
> Make it build with ghc-9.12

- changelog.d/1317-server-sent-events
- servant-client-core/servant-client-core.cabal
- servant-client-core/src/Servant/Client/Core/HasClient.hs
- servant-client-core/src/Servant/Client/Core/ServerSentEvents.hs
- servant-client-core/test/Servant/Client/Core/ServerSentEventsSpec.hs
- servant/servant.cabal
- servant/src/Servant/API.hs
- servant/src/Servant/API/ContentTypes.hs
- servant/src/Servant/API/ServerSentEvents.hs
- servant/src/Servant/Types/SourceT.hs
Picking up #1317.
I rebased the changes to be a single commit after adding the fix on top, but there's also the unrebased version: https://github.com/haskell-servant/servant/compare/master...voidus:servant:feature/server-sent-events-unrebased
Reproducing the old PR description below:
---
This PR is an attempt to implement [SSE](https://www.w3.org/TR/2009/WD-eventsource-20090421/) for the Servant client-side.
---
```haskell
import qualified Data.Aeson                           as Aeson
import           Network.HTTP.Client.TLS
import           Servant.API
import           Servant.Client.Core.ServerSentEvents (JsonEventStreamT (..))
import           Servant.Client.Streaming
import           Servant.Types.SourceT                (foreachStep)
data NewsEntry
instance Show NewsEntry
instance …
```
> Client-side support for server-sent events (SSE)

- changelog.d/issue-1232
- servant/src/Servant/Links.hs
> Exported Servant.Links.addQueryParam

- doc/cookbook/file-upload/FileUpload.lhs
- doc/tutorial/Server.lhs
Most other links in the cookbook / tutorial are already links without version (which leads to hackage resolving to latest package version).
> Don't hardcode package versions in cookbook / tutorial links

- cabal.project
- doc/cookbook/expose-prometheus/ExposePrometheus.lhs
- doc/cookbook/expose-prometheus/expose-prometheus.cabal
- doc/cookbook/index.rst
@tchoutri :kissing:
Not sure when I'll have time to address comments, so feel free to directly edit the PR.
The code itself is inspired from what I do in [prodapi](https://github.com/lucasdicioccio/prodapi/blob/master/prodapi/src/Prod/Prometheus.hs).
> Add cookbook to expose Prometheus counters.

- changelog.d/pr-1843
- servant-server/src/Servant/Server/Internal/ErrorFormatter.hs
I'm not sure it's the correct fix, I've only set `errBody`.
closes #1790.
> Set `errBody` of `defaultErrorFormatters.notFoundErrorFormatter` in `servant-server` (#1790)

- changelog.d/pr-1844
- servant-client-core/src/Servant/Client/Core/HasClient.hs
- servant-docs/golden/comprehensive.md
- servant-docs/src/Servant/Docs/Internal.hs
- servant-foreign/src/Servant/Foreign/Internal.hs
- servant-server/src/Servant/Server/Internal.hs
- servant-swagger/src/Servant/Swagger/Internal.hs
- servant/src/Servant/API.hs
- servant/src/Servant/API/Description.hs
- servant/src/Servant/Links.hs
- servant/src/Servant/Test/ComprehensiveAPI.hs
Add `OperationId`, which can direct code and docs generation.
> Add `OperationId`
