haskell-servant/servant

src/Servant/API.hs, src/Servant/API/Delete.hs, src/Servant/API/Get.hs, src/Servant/API/Header.hs, src/Servant/API/Post.hs, src/Servant/API/Put.hs, src/Servant/API/Sub.hs, src/Servant/Common/Text.hs, src/Servant/QQ.hs, src/Servant/Utils/Links.hs, test/Servant/QQSpec.hs, test/Servant/Utils/LinksSpec.hs
=> Explicit import lists

servant.cabal, src/Servant/Common/Text.hs, test/Servant/API/ContentTypesSpec.hs, test/Servant/Common/TextSpec.hs
And add FromText/ToText tests.
=> Fix Integer FromText instance.

servant-client/CHANGELOG.md, servant-client/src/Servant/Client.hs, servant-client/test/Servant/ClientSpec.hs, servant-docs/CHANGELOG.md, servant-docs/example/greet.hs, servant-docs/src/Servant/Docs/Internal.hs, servant-jquery/CHANGELOG.md, servant-jquery/src/Servant/JQuery/Internal.hs, servant-server/CHANGELOG.md, servant-server/example/greet.hs, servant-server/src/Servant/Server/Internal.hs, servant-server/test/Servant/ServerSpec.hs, servant/CHANGELOG.md, servant/src/Servant/API/Delete.hs, servant/src/Servant/Utils/Links.hs, servant/test/Servant/Utils/LinksSpec.hs
@alpmestan @jkarni This could use a good check over just to be sure I got this right. Please let me know if I missed anything or did something wrong. All tests are passing in servant, servant-client, servant-docs, servant-jquery, and servant-server. Fixes #33.
=> modify delete to allow for response body

servant-examples/servant-examples.cabal
=> Upper bounds to base for servant-examples

scripts/test-all.sh, servant-server/servant-server.cabal, servant-server/test/Doctests.hs, servant/servant.cabal, servant/test/Doctests.hs
=> scripts: install all of the servant ecosystem at once, for consistent dependencies

servant-client/README.md, servant-client/src/Servant/Client.hs, servant-docs/README.md, servant-docs/src/Servant/Docs.hs
=> Update examples for servant-docs and servant-client

servant/src/Servant/Utils/Links.hs
=> servant: clean up some white spaces, add link explaining why Or works.

servant-client/CHANGELOG.md, servant-client/src/Servant/Client.hs, servant-client/test/Servant/ClientSpec.hs
Let me know if anything needs changed.
=> Allow zero content types on delete. fixes #69

servant-server/CHANGELOG.md, servant-server/servant-server.cabal
Cf. https://github.com/fpco/stackage/issues/572
=> Bump attoparsec

servant-server/CHANGELOG.md, servant-server/servant-server.cabal
See https://github.com/fpco/stackage/issues/610
=> Bump 'either' upper-bound

servant-examples/auth-combinator/auth-combinator.hs, servant-server/servant-server.cabal, servant-server/src/Servant/Server.hs, servant-server/src/Servant/Server/Internal.hs, servant-server/src/Servant/Server/Internal/PathInfo.hs, servant-server/src/Servant/Server/Internal/Router.hs, servant-server/src/Servant/Server/Internal/RoutingApplication.hs, servant-server/test/Servant/ServerSpec.hs
I'd like to open this up for discussion and (ideally) merging.
This is to a certain extent ongoing work and should probably be refined further before the next major release, to keep breaking changes for end users to a minimum.
The two main aspects this PR addresses are:
* Complexity of routing is much better. We don't perform linear testing where possible, but instead dispatch via lookup tables. @jkarni has performed some benchmarking and it looks quite promising.
* We delay matching of "non-path" components (such as request headers and the request body) and of captures until we are sure that a route otherwise matches. This saves work, and allows us to produce better error codes in many cases. This addresses issue #73, and will hopefully allow progress on #70. (I have tested that the …
=> Improved routing

servant-client/src/Servant/Common/BaseUrl.hs, servant-client/src/Servant/Common/Req.hs
=> Use MonadThrow instead of Either in the signature of parseBaseUrl

servant-server/servant-server.cabal, servant/servant.cabal
=> Bump string-conversions

scripts/lib/common.sh, scripts/test-all.sh, servant/test/Servant/API/ContentTypesSpec.hs
Hopefully this helps with the travis builds.
=> travis retry

servant/src/Servant/Utils/Links.hs, servant/test/Servant/Utils/LinksSpec.hs
This can only go in 0.5 though, can't be cherry-picked in 0.4.
=> Tweak the HasLink instance for QueryParam, fixes #129

servant-client/src/Servant/Common/Req.hs, servant-client/test/Servant/ClientSpec.hs
This is what I meant by using SomeException
=> servant-client: Hide HttpException by wrapping it in SomeException

servant-jquery/src/Servant/JQuery.hs
Also remove some redundant newlines in generated JS.
I have modified your commit a little in this PR @bwo, I'm now happy with this commit.
Please review & merge if OK @alpmestan.
This closes #122, fixes #148, and resolves #149.
=> servant-jquery: set content type to application/json on POST

scripts/bump-versions.sh, scripts/lib/common.sh, servant-blaze/servant-blaze.cabal, servant-client/servant-client.cabal, servant-docs/CHANGELOG.md, servant-docs/servant-docs.cabal, servant-docs/src/Servant/Docs/Internal.hs, servant-docs/test/Servant/DocsSpec.hs, servant-examples/CHANGELOG.md, servant-examples/servant-examples.cabal, servant-examples/tutorial/T4.hs, servant-jquery/CHANGELOG.md, servant-jquery/servant-jquery.cabal, servant-jquery/src/Servant/JQuery.hs, servant-lucid/servant-lucid.cabal, servant-server/servant-server.cabal, servant/CHANGELOG.md, servant/servant.cabal, servant/src/Servant/Utils/Links.hs
WIP, review only, no merge yet.
I'm thinking of naming this: 0.4.3
I think it's a nice name.
If we are all OK with the name and the commits included I'll bump and add some words to the changelog, and make the tests all happy, etc.
=> Bugfix release

servant/CHANGELOG.md, servant/src/Servant/Utils/Links.hs, servant/test/Servant/Utils/LinksSpec.hs
The intention was obviously to ignore them, but we weren't doing so
correctly.
=> Fix isElem for Header.

servant-js/src/Servant/JS/Angular.hs, servant-js/src/Servant/JS/Internal.hs, servant-js/src/Servant/JS/JQuery.hs, servant-js/src/Servant/JS/Vanilla.hs
Just a simple option to let the JavaScriptGenerator prepend some string to the AJAX calls
=> Add urlPrefix to CommonGeneratorOptions

servant-server/servant-server.cabal
=> Bump warp upper bound.

servant-server/src/Servant/Server/Internal.hs, servant-server/test/Servant/ServerSpec.hs
=> Respond with Head to all Get requests

servant-server/README.md, servant-server/servant-server.cabal
=> update readme for servant-server

servant/servant.cabal
=> Dead link in servant.cabal

servant/servant.cabal
=> Remove broken links

servant-mock/LICENSE, servant-mock/Setup.hs, servant-mock/default.nix, servant-mock/example/main.hs, servant-mock/servant-mock.cabal, servant-mock/shell.nix, servant-mock/src/Servant/Mock.hs, sources.txt, stack.yaml
=> Add servant-mock to 0.4

servant-client/README.md, servant-client/servant-client.cabal, servant-client/src/Servant/Client.hs, servant-client/src/Servant/Common/Req.hs, servant-client/test/Servant/ClientSpec.hs, servant-examples/hackage/hackage.hs, servant-examples/servant-examples.cabal, servant-examples/tutorial/T3.hs, servant-examples/tutorial/T5.hs, servant-examples/tutorial/T7.hs, servant-examples/tutorial/T8.hs, servant-mock/src/Servant/Mock.hs, servant-server/CHANGELOG.md, servant-server/example/greet.hs, servant-server/servant-server.cabal, servant-server/src/Servant/Server.hs, servant-server/src/Servant/Server/Internal.hs, servant-server/src/Servant/Server/Internal/Enter.hs, servant-server/src/Servant/Server/Internal/RoutingApplication.hs, servant-server/test/Servant/Server/Internal/EnterSpec.hs, servant-server/test/Servant/ServerSpec.hs, stack.yaml
=> Drop EitherT in favor of ExceptT

servant-server/src/Servant/Server/Internal.hs
=> Document octet-stream default RFC.

servant-docs/CHANGELOG.md, servant-docs/example/greet.hs, servant-docs/src/Servant/Docs.hs, servant-docs/src/Servant/Docs/Internal.hs, servant-docs/test/Servant/DocsSpec.hs, servant-examples/tutorial/T10.hs
=> Simplify ToSample (remove redundant second parameter)

servant-client/CHANGELOG.md, servant-client/src/Servant/Client.hs, servant-client/src/Servant/Common/Req.hs, servant-client/test/Servant/ClientSpec.hs, servant-examples/hackage/hackage.hs, servant-examples/servant-examples.cabal, servant-examples/tutorial/T8.hs, servant/CHANGELOG.md, servant/src/Servant/API/Alternative.hs
=> Pass in Manager as argument to 'client'

servant-client/CHANGELOG.md, servant-client/src/Servant/Client.hs, servant-client/src/Servant/Common/Req.hs, servant-client/test/Servant/ClientSpec.hs
=> More generous acceptable status codes for servant-client

servant-server/src/Servant/Server.hs, servant-server/src/Servant/Server/Internal/Router.hs, servant-server/test/Servant/ServerSpec.hs
this function is a waste product of something we ended up doing differently, but @jkarni and I but like it a lot.  If you want to have it, I can write the test code.  If you think we should wait for use case, feel free to close this pr.
=> fmapRouter.

servant-js/README.md, servant-js/docs.sh, servant-js/servant-js.cabal
=> Replace servant-jquery with servant-js in remaining files

servant-js/src/Servant/JS/Vanilla.hs
This should fix issue #285 . 
I'm wondering if we could write some sort of regression test suit using `nodejs` or http://phantomjs.org/ to catch these kind of bugs.
=> WIP: Fix issue #285

servant/servant.cabal, servant/src/Servant/Utils/Links.hs, servant/test/Doctests.hs, servant/test/Servant/Utils/LinksSpec.hs
=> Fix loop in IsSubList

servant-mock/servant-mock.cabal, servant-server/servant-server.cabal
=> Bump wai and warp upper bound to < 3.3.

CONTRIBUTING.md, README.md
Comments and suggestions very welcome!
=> First pass at CONTRIBUTING

servant-docs/src/Servant/Docs/Internal.hs, servant-docs/test/Servant/DocsSpec.hs
=> Re-add missing Header instance for docs.

servant-docs/src/Servant/Docs/Internal.hs, servant-docs/test/Servant/DocsSpec.hs
=> Fix extra quotes in Verb headers for docs.

servant-blaze/LICENSE, servant-blaze/servant-blaze.cabal, servant-cassava/LICENSE, servant-cassava/servant-cassava.cabal, servant-client/LICENSE, servant-client/servant-client.cabal, servant-docs/LICENSE, servant-docs/servant-docs.cabal, servant-examples/LICENSE, servant-examples/servant-examples.cabal, servant-foreign/LICENSE, servant-foreign/servant-foreign.cabal, servant-js/LICENSE, servant-js/servant-js.cabal, servant-lucid/LICENSE, servant-lucid/servant-lucid.cabal, servant-mock/LICENSE, servant-mock/servant-mock.cabal, servant-server/LICENSE, servant-server/servant-server.cabal, servant/LICENSE, servant/servant.cabal
=> Change copyright to servant contributors

servant-server/src/Servant/Server/Internal.hs, servant-server/src/Servant/Server/Internal/RoutingApplication.hs, servant-server/test/Servant/Server/ErrorSpec.hs
=> Remove memoReqBody.

doc/tutorial/index.rst
Resolves https://github.com/haskell-servant/servant/issues/367
=> Use rst links syntax (it's not a markdown)

servant-client/test/Servant/ClientSpec.hs, servant-examples/auth-combinator/auth-combinator.hs, servant-examples/socket-io-chat/socket-io-chat.hs, servant-examples/tutorial/T1.hs, servant-examples/tutorial/T10.hs, servant-examples/tutorial/T2.hs, servant-examples/tutorial/T3.hs, servant-examples/tutorial/T4.hs, servant-examples/tutorial/T5.hs, servant-examples/tutorial/T6.hs, servant-examples/tutorial/T7.hs, servant-examples/tutorial/T9.hs, servant-examples/wai-middleware/wai-middleware.hs, servant-mock/example/main.hs, servant-mock/src/Servant/Mock.hs, servant-mock/test/Servant/MockSpec.hs, servant-server/example/greet.hs, servant-server/src/Servant/Server.hs, servant-server/src/Servant/Server/Internal/RoutingApplication.hs, servant-server/test/Servant/Server/ErrorSpec.hs, servant-server/test/Servant/Server/Internal/EnterSpec.hs, servant-server/test/Servant/Server/UsingConfigSpec.hs, servant-server/test/Servant/ServerSpec.hs, servant-server/test/Servant/Utils/StaticFilesSpec.hs
And keep the old signature for 'serve'
=> Add 'serveWithConfig'.

servant-server/servant-server.cabal
Solves #374 for the 0.4 branch.
=> Bump aeson version.

servant-server/src/Servant/Server/Internal/ServantErr.hs
Being able to throw an error is useful at times.
=> Make ServantErr throwable

servant-js/servant-js.cabal, servant-js/test/Servant/JSSpec.hs, servant-server/servant-server.cabal, servant-server/src/Servant/Server/Internal.hs, servant-server/src/Servant/Server/Internal/Enter.hs, servant-server/src/Servant/Server/Internal/RoutingApplication.hs, servant/servant.cabal, servant/src/Servant/API/Alternative.hs, servant/src/Servant/API/ContentTypes.hs, servant/src/Servant/API/Internal/Test/ComprehensiveAPI.hs, servant/src/Servant/API/ResponseHeaders.hs, servant/src/Servant/Utils/Links.hs, stack-ghc-7.8.4.yaml, stack.yaml
basically #403
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/haskell-servant/servant/404)
=> prefer base-compat to CPP macros

doc/tutorial/ApiType.lhs, doc/tutorial/Authentication.lhs, doc/tutorial/Server.lhs
=> Add basic auth to tutorial

servant/src/Servant/API/Raw.hs
=> Fix link to serveDirectory.

servant-server/src/Servant/Server/Internal/ServantErr.hs
It's more useful to see some examples when we're trying to see which error to return.
=> Document http error codes

doc/tutorial/Authentication.lhs, doc/tutorial/index.rst, doc/tutorial/tutorial.cabal
@aaronlevin it seems the CI is failing on the tutorial code, would you mind taking a look when you get a chance to? so that we can publish your very own section of the tutorial :)
=> include Authentication.lhs in tutorial project and table of contents

.travis.yml, doc/tutorial/tutorial.cabal, scripts/README.md, scripts/bump-versions.sh, servant-blaze/servant-blaze.cabal, servant-cassava/servant-cassava.cabal, servant-client/CHANGELOG.md, servant-client/servant-client.cabal, servant-docs/servant-docs.cabal, servant-foreign/servant-foreign.cabal, servant-js/servant-js.cabal, servant-lucid/servant-lucid.cabal, servant-mock/servant-mock.cabal, servant-server/CHANGELOG.md, servant-server/servant-server.cabal, servant/servant.cabal, sources.txt, travis.sh
I'd like to make a new release to hackage. I bumped the versions but also made a few changes to some scripts (CI, the version bumping script, etc.). I'd appreciate a review.
=> New release

servant-client/src/Servant/Client.hs
=> re-export `ClientM` from `Servant.Client`.

servant-server/test/Servant/ServerSpec.hs
Continuing with the work from https://github.com/haskell-servant/servant/pull/445, this adds an explicit test to ensure General Authentication handles Raw endpoints appropriately.
The previous behaviour was correct, but this test will ensure that any future changes are correct w.r.t. Raw.
=> Add test: Gen Auth properly supports Raw endpoints

sources.txt
I think both for the release script and for CI it makes sense to prefer these
two packages.
=> sources.txt: prefer servant-server and servant-client

servant-server/src/Servant/Server/Experimental/Auth.hs, servant-server/test/Servant/ServerSpec.hs
just to clarify on how to use it properly
=> add one more test for general auth

servant-server/CHANGELOG.md
=> update servant-server's changelog for 0.6.1

doc/tutorial/Authentication.lhs, doc/tutorial/Server.lhs, servant-client/test/Servant/ClientSpec.hs, servant-mock/src/Servant/Mock.hs, servant-server/example/greet.hs, servant-server/src/Servant/Server.hs, servant-server/src/Servant/Server/Experimental/Auth.hs, servant-server/src/Servant/Server/Internal.hs, servant-server/src/Servant/Server/Internal/RoutingApplication.hs, servant-server/src/Servant/Server/Internal/ServantErr.hs, servant-server/test/Servant/Server/Internal/EnterSpec.hs, servant-server/test/Servant/Server/StreamingSpec.hs, servant-server/test/Servant/Server/UsingContextSpec.hs, servant-server/test/Servant/ServerSpec.hs
=> Introduce a `Handler` alias for `ExceptT ServantErr IO`

servant-js/src/Servant/JS.hs, servant-js/src/Servant/JS/Internal.hs
(I use master version as extra-deps with stack and those warnings were annoying me in ghci)
=> Fix some warnings

doc/examples.md, doc/index.rst
=> doc: add a section about example projects

servant/src/Servant/API/ResponseHeaders.hs
Issue: https://github.com/haskell-servant/servant/issues/396
=> Allow duplicate headers

servant-client/test/Servant/ClientSpec.hs, servant-server/src/Servant/Server.hs, servant-server/test/Servant/Server/RouterSpec.hs
=> Re-export Application.

servant-foreign/servant-foreign.cabal, servant-mock/servant-mock.cabal
For servant-foreign and servant-mock.
=> Add source-repo and bug report

servant-client/README.md
=> Remove host param from servant-client README.

servant-client/servant-client.cabal, servant-server/servant-server.cabal, servant/servant.cabal
(cherry picked from commit a0d5ed9aea10757caafa7d9654cb6f912d75a350)
=> Add bounds to servant, servant-server and servant-clients

doc/tutorial/tutorial.cabal, servant-docs/example/greet.hs, servant-docs/src/Servant/Docs/Internal.hs, servant-foreign/src/Servant/Foreign/Internal.hs, servant-foreign/test/Servant/ForeignSpec.hs, servant-js/servant-js.cabal, servant-js/src/Servant/JS.hs, servant-js/src/Servant/JS/Internal.hs, servant-js/test/Servant/JSSpec.hs, servant-js/test/Servant/JSSpec/CustomHeaders.hs, servant-mock/src/Servant/Mock.hs, servant-server/example/greet.hs, servant-server/src/Servant/Server.hs, servant-server/test/Servant/Server/RouterSpec.hs, servant-server/test/Servant/ServerSpec.hs, servant/src/Servant/API/ContentTypes.hs, servant/src/Servant/API/Internal/Test/ComprehensiveAPI.hs, servant/src/Servant/Utils/Links.hs, servant/test/Servant/Utils/LinksSpec.hs
=> Replace () with NoContent

doc/tutorial/tutorial.cabal, servant-client/servant-client.cabal, servant-docs/servant-docs.cabal, servant-foreign/servant-foreign.cabal, servant-js/servant-js.cabal, servant-mock/servant-mock.cabal, servant-server/servant-server.cabal, servant/CHANGELOG.md, servant/servant.cabal
Can someone please review whether a minor version bump is allowed? And whether it's what we want?
Thanks!
@haskell-servant/maintainers
=> release 0.8

servant-client/src/Servant/Client.hs, servant-client/test/Servant/ClientSpec.hs, servant-docs/src/Servant/Docs/Internal.hs, servant-docs/test/Servant/DocsSpec.hs, servant-foreign/src/Servant/Foreign/Internal.hs, servant-foreign/test/Servant/ForeignSpec.hs, servant-mock/src/Servant/Mock.hs, servant-server/src/Servant/Server/Internal.hs, servant-server/src/Servant/Server/Internal/Router.hs, servant-server/src/Servant/Server/Internal/RoutingApplication.hs, servant-server/test/Servant/ServerSpec.hs, servant/src/Servant/API.hs, servant/src/Servant/API/Capture.hs, servant/src/Servant/API/Internal/Test/ComprehensiveAPI.hs, servant/src/Servant/Utils/Links.hs, servant/test/Servant/Utils/LinksSpec.hs
Closes #257.
Builds on @fizruk's work in #347, but updated for recent changes to servant, and including support for foreign & docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/haskell-servant/servant/519)
=> CaptureAll combinator - take #2

doc/requirements.txt
=> docs: bump Sphinx version

servant/CHANGELOG.md
=> add changelog entry for `CaptureAll`

doc/tutorial/Javascript.lhs, doc/tutorial/test/JavascriptSpec.hs, servant-js/src/Servant/JS.hs
Contributed by freezeboy in PR #11 -
https://github.com/haskell-servant/haskell-servant.github.io/pull/11/files
=> Add more JS documentation.

servant-client/servant-client.cabal, servant-client/test/Servant/ClientSpec.hs, servant-server/servant-server.cabal, servant-server/src/Servant/Server/Internal.hs, servant/CHANGELOG.md, servant/servant.cabal, servant/src/Servant/API.hs, servant/src/Servant/API/ContentTypes.hs, servant/test/Servant/API/ContentTypesSpec.hs, stack-ghc-7.8.4.yaml, stack-ghc-8.0.1.yaml, stack.yaml
Replaces #582 . I'm doing this because having branches with numbers as names confuses read-the-docs, and I want to delete that one.
=> Use http api forms

servant-server/src/Servant/Server/Internal/ServantErr.hs
What I've been working on during Hacφ.
=> add err418

doc/tutorial/Server.lhs
Fixes #608 
cc: @thoughtpolice
=> Add more documentation about response headers to tutorial.

servant-server/src/Servant/Server/Internal/ServantErr.hs
Implemented ServantErr of HTTP status code 422(Unprocessable Entity).
Definition of Unprocessable Entity: https://tools.ietf.org/html/rfc2518#section-10.3
=> add HTTP status code 422

servant-client/CHANGELOG.md, servant-client/servant-client.cabal, servant-client/src/Servant/Common/Req.hs, servant-server/CHANGELOG.md, servant/CHANGELOG.md
=> Add MonadBaseControl IO ClientM instance

servant/CHANGELOG.md, servant/src/Servant/API.hs, servant/src/Servant/Utils/Links.hs, servant/test/Servant/Utils/LinksSpec.hs, stack.yaml
Resolves #527, supersedes #572
=> Bug fix for haslink

servant-foreign/CHANGELOG.md, servant-foreign/src/Servant/Foreign/Inflections.hs, servant-foreign/src/Servant/Foreign/Internal.hs, servant-foreign/test/Servant/ForeignSpec.hs
Supersedes #556 
Resolves #191
=> Fix js function identifiers

servant-client/servant-client.cabal, servant-client/src/Servant/Common/Req.hs, servant-client/test/Servant/ClientSpec.hs, servant-server/CHANGELOG.md, servant-server/servant-server.cabal, servant-server/src/Servant/Server.hs, servant-server/src/Servant/Server/Experimental/Auth.hs, servant-server/src/Servant/Server/Internal.hs, servant-server/src/Servant/Server/Internal/Handler.hs, servant-server/src/Servant/Server/Internal/RoutingApplication.hs, servant-server/src/Servant/Server/Internal/ServantErr.hs, servant-server/test/Servant/Server/ErrorSpec.hs, servant-server/test/Servant/ServerSpec.hs
=> Make Handler a newtype

doc/tutorial/Client.lhs
I add two minor commits. Each with commit messages describing the changes.
Also: This library looks amazing! Good job all contributors! :)
=> Fixes to tutorial (Client.lhs file)

doc/tutorial/ApiType.lhs
https://github.com/haskell-servant/servant/blob/master/doc/tutorial/ApiType.lhs#L20
=> Make type consistent with whats written on line 20

doc/tutorial/Server.lhs
Briefly address #692. Section can be improved, but I'll leave it for the volunteers.
=> Briefly correct ExceptT mentions into Handler

servant-server/src/Servant/Server.hs
=> Servant.Server: Re-export missing error codes

servant-client/servant-client.cabal, stack-ghc-7.8.4.yaml, stack-ghc-8.0.2.yaml, stack.yaml
=> Bump lower bound for http-api-data

doc/tutorial/Docs.lhs, servant-client/test/Servant/ClientSpec.hs, servant-server/servant-server.cabal, servant-server/src/Servant/Server.hs, servant-server/src/Servant/Server/Internal.hs, servant-server/src/Servant/Utils/StaticFiles.hs, servant-server/test/Servant/ServerSpec.hs, servant/servant.cabal, servant/src/Servant/Utils/Enter.hs
Supersedes #282
ping @avieth
By having `ServerT Raw m = Tagged m Application` the solution is quite generic. I'll see how if it can be applied to `servant-client` too.
=> ServerT Raw m = Tagged m Application

servant-server/test/Servant/Server/Internal/ContextSpec.hs, servant/CHANGELOG.md, servant/src/Servant/API/Alternative.hs, servant/src/Servant/API/Sub.hs
=> Lower infix precedence for (:>) and (:<|>)

servant-docs/CHANGELOG.md, servant-docs/src/Servant/Docs/Internal.hs
Similar to what's already done for request bodies.
=> List content type with response examples

servant-client/src/Servant/Client/Internal/HttpClient.hs
Added the secure fields to the http-client request in the function `requestToClientRequest` as per issue #821
=> Fix issue #821

servant/CHANGELOG.md
This PR  is too check how markup is rendered
=> Open up significant changes in 0.12 [ci skip]

README.md
Very minor change to fix a md problem that prevented the table rendering.
=> Minor md fix for table rendering

doc/cookbook/jwt-and-basic-auth/JWTAndBasicAuth.lhs, doc/cookbook/jwt-and-basic-auth/jwt-and-basic-auth.cabal
Perhaps it can use more editing, but here's what I've got for now.
=> Cookbook recipe for JWT with basic authentication

.gitignore, cabal.project, doc/cookbook/BasicAuth.lhs, doc/cookbook/basic-auth/BasicAuth.lhs, doc/cookbook/basic-auth/basic-auth.cabal, doc/cookbook/cabal.project, doc/cookbook/db-postgres-pool/PostgresPool.lhs, doc/cookbook/db-postgres-pool/db-postgres-pool.cabal, doc/cookbook/db-sqlite-simple/DBConnection.lhs, doc/cookbook/db-sqlite-simple/db-sqlite-simple.cabal, doc/cookbook/file-upload/FileUpload.lhs, doc/cookbook/file-upload/file-upload.cabal, doc/cookbook/https/Https.lhs, doc/cookbook/https/https.cabal, doc/cookbook/index.rst, doc/cookbook/jwt-and-basic-auth/JWTAndBasicAuth.lhs, doc/cookbook/jwt-and-basic-auth/jwt-and-basic-auth.cabal, doc/cookbook/structuring-apis/StructuringApis.lhs, doc/cookbook/structuring-apis/structuring-apis.cabal, doc/index.rst, nix/README.md, nix/shell.nix
It's nowhere near ready, nothing very interesting so far.
=> [Docs] Cookbook

doc/tutorial/Authentication.lhs, doc/tutorial/tutorial.cabal
=> Improve authentication docs

cabal.project, doc/cookbook/cabal.project, doc/cookbook/index.rst, doc/cookbook/using-custom-monad/UsingCustomMonad.lhs, doc/cookbook/using-custom-monad/using-custom-monad.cabal
=> Added new cookbook recipe for using custom monad

doc/tutorial/ApiType.lhs
Thanks to [a fellow haskeller](https://twitter.com/markeibes/status/964054303638999040) for spotting it.
=> Fix typo in tutorial

doc/tutorial/Server.lhs
UserAPI1 is already defined at line 64.
=> Remove duplicate type declaration

servant-client-ghcjs/src/Servant/Client/Internal/XhrClient.hs
Introduces support for both sending and receiving binary data in `servant-client-ghcjs`.
Previously, the conversion to String before going to Bytestring would fail with any requests that sent or received binary data. With ArrayBuffers in the backend, sending Binary encoded data now works.
Also added a test case to https://github.com/FPtje/servant-client-ghcjs-test to test both sending and receiving of Binary data. It works and the tests don't show any regression.
One important note: I see that some recent version of servant has added a `streamingRequest` to the `RunClient`class. It is't implemented in servant-client-ghcjs, and this PR doesn't add it.
=> servant-client-ghcjs: Support binary requests

.travis.yml, doc/cookbook/basic-auth/basic-auth.cabal, doc/cookbook/db-postgres-pool/db-postgres-pool.cabal, doc/cookbook/db-sqlite-simple/db-sqlite-simple.cabal, doc/cookbook/file-upload/file-upload.cabal, doc/cookbook/generic/generic.cabal, doc/cookbook/https/https.cabal, doc/cookbook/jwt-and-basic-auth/jwt-and-basic-auth.cabal, doc/cookbook/pagination/dummy/Pagination.lhs, doc/cookbook/pagination/pagination.cabal, doc/cookbook/structuring-apis/structuring-apis.cabal, doc/cookbook/using-custom-monad/using-custom-monad.cabal, doc/cookbook/using-free-client/using-free-client.cabal, doc/tutorial/tutorial.cabal, servant-client-core/servant-client-core.cabal, servant-client/servant-client.cabal, servant-docs/servant-docs.cabal, servant-foreign/servant-foreign.cabal, servant-server/servant-server.cabal, servant/servant.cabal, stack.yaml
Let's bump lower bounds to whatever is in LTS close to the release date.
=> Support only GHC-8.0+

servant-server/src/Servant/Utils/StaticFiles.hs
=> Fix minor typo in deprecation warning

servant/src/Servant/API.hs, servant/src/Servant/API/Verbs.hs
Adding PutCreated to be a little bit more aligned with RFC 7231
=> Add put created verb

doc/tutorial/Server.lhs
There are so much waste in the universe and we need to change the situation. The better usage the better habits of one leads a positive attitude of everyone.
You always hear guys complain about the cost of storage so it's appreciated as fuck. Decreasing line by 1 symbol leads to less disk space usage (up to 2 bytes at a time)!
=> Remove redundant point

servant-docs/golden/comprehensive.md, servant-docs/servant-docs.cabal, servant-docs/src/Servant/Docs/Internal.hs, servant-docs/test/Servant/DocsSpec.hs, servant-docs/test/Spec.hs, servant/src/Servant/Test/ComprehensiveAPI.hs
Resolves https://github.com/haskell-servant/servant/issues/990
=> Golden servant docs

servant/src/Servant/API.hs, servant/src/Servant/API/ResponseHeaders.hs
=> Add lookupResponseHeader

servant/servant.cabal, servant/src/Servant/Types/SourceT.hs
The generated instances are pure-ish; errorless.
=> Add Arbitrary (SourceT m a) and StepT m a instances

doc/cookbook/using-custom-monad/UsingCustomMonad.lhs
Took me a decent amount of googling to figure this out. I believe this is the currently recommended way? As a relatively new user, I was surprised this was not available in the core package.
cc @cdepillabout
Ref #785 and #819.
=> Add note to custom monad documentation about what to do with Raw endpoints

servant/servant.cabal, servant/src/Servant/API/ContentTypes.hs
This comes handy for `runClientM :: NFData a => ClientM a -> ClientEnv -> IO (Either ServantError a)`
=> Add NoContent instance for NFData

.travis.yml, cabal.project, doc/cookbook/cabal.project, doc/cookbook/index.rst, doc/cookbook/open-id-connect/OpenIdConnect.cabal, doc/cookbook/open-id-connect/OpenIdConnect.lhs
=> Adding OIDC Cookbook

servant/servant.cabal
=> Allow singleton-bool 0.1.5

servant-client-core/src/Servant/Client/Core/HasClient.hs
=> HasClient instance for Stream with Headers

servant/servant.cabal
@phadej, removes and adds unused / missing extensions.
=> Remove more unused extensions

doc/cookbook/testing/Testing.lhs
Ran into an issue today running tests based on these examples on Gitlab CI. The tests were either tried too soon or the port was unavailable. `Warp.testWithApplication` seems to take care of order and shutdown. 
It should also be fine to use hspecs `parallel` since every test gets its own port. I left it out cause it seemed a bit unnecessary for this example. 
The elasticsearch example is not updated and still uses bracket. It didn't seem entirely straightforward to implement due to the setting of the port with the action.
=> Testing docs, use Warp.testWithApplication to prevent race condition

servant-client-core/src/Servant/Client/Core/HasClient.hs, servant-client/test/Servant/ClientTestUtils.hs, servant-client/test/Servant/FailSpec.hs
=> Fix Verb with headers checking content type differently

doc/tutorial/ApiType.lhs, doc/tutorial/Server.lhs, servant-client-core/src/Servant/Client/Core/HasClient.hs, servant-client/test/Servant/ClientTestUtils.hs, servant-docs/golden/comprehensive.md, servant-docs/src/Servant/Docs/Internal.hs, servant-foreign/src/Servant/Foreign/Internal.hs, servant-http-streams/test/Servant/ClientSpec.hs, servant-server/src/Servant/Server/Internal.hs, servant-server/test/Servant/ServerSpec.hs, servant/src/Servant/API.hs, servant/src/Servant/API/Verbs.hs, servant/src/Servant/Links.hs, servant/src/Servant/Test/ComprehensiveAPI.hs
Rebased #1219. Resolves #1028.
=> Pull 1219: no content verb 1028

.travis.yml, cabal.project, servant-client/CHANGELOG.md, servant-client/servant-client.cabal, servant-client/src/Servant/Client/Internal/HttpClient.hs, servant-http-streams/CHANGELOG.md, servant-http-streams/src/Servant/HttpStreams/Internal.hs, servant-jsaddle/servant-jsaddle.cabal
Closes https://github.com/haskell-servant/servant/issues/1227
=> Build jsaddle with GHC-8.8

.travis.yml, cabal.haskell-ci, doc/tutorial/tutorial.cabal, servant-jsaddle/servant-jsaddle.cabal
- Allow newer js-jquery in tutorial
- use bionic on Travis
- allow newer hspec in servant-jsaddle
=> Small updates

doc/tutorial/Authentication.lhs
I guess some sample curl commands on the tutorial are wrong.
=> I guess some sample curl commands are wrong.

.travis.yml, cabal.project
Dependencies are updated to allow servant-0.17
=> Drop most allow-newer in cabal.project

servant-server/servant-server.cabal
=> Allow base64-bytestring 1.1

servant/servant.cabal
=> Allow QuickCheck 2.14

servant-foreign/servant-foreign.cabal
https://github.com/ekmett/lens/blob/v4.19.1/CHANGELOG.markdown
=> Allow lens 4.19

servant/servant.cabal
=> Allow aeson 1.5

servant-client-core/servant-client-core.cabal, servant-docs/servant-docs.cabal, servant-server/servant-server.cabal
=> Allow aeson 1.5 in all components

servant/servant.cabal, servant/src/Servant/API/Status.hs
=> Add KnownStatus typeclass

doc/cookbook/hoist-server-with-context/HoistServerWithContext.lhs
=> Docs: Hoist Server "Footnote"

.travis.yml, cabal.project, doc/cookbook/testing/testing.cabal
Now we can finally enable back the cookbook :)
=> Reenable cookbook-testing

doc/tutorial/Server.lhs
Fixed an awkward wording in the Server tutorial.
=> Minor rewording in Server tutorial

servant-server/servant-server.cabal, servant/servant.cabal
=> Allow http-api-data 0.4.2

servant-server/src/Servant/Server/Internal.hs
https://github.com/haskell-servant/servant/commit/f5d9983381b96ee1ce03e97e3e1d4982e1c92972
=> Fix docs: emptyAPIServer -> emptyServer

servant-server/servant-server.cabal
=> Allow hspec-wai 0.11

servant-client-core/CHANGELOG.md, servant-client-core/servant-client-core.cabal, servant-client/CHANGELOG.md, servant-client/servant-client.cabal, servant-docs/CHANGELOG.md, servant-docs/servant-docs.cabal, servant-http-streams/CHANGELOG.md, servant-http-streams/servant-http-streams.cabal, servant-server/CHANGELOG.md, servant-server/servant-server.cabal, servant/CHANGELOG.md, servant/servant.cabal
After we release this on Hackage we can add servant stuff back to Stackage.
=> Bump versions

servant-client-core/servant-client-core.cabal, servant-client/servant-client.cabal, servant-http-streams/servant-http-streams.cabal, servant-server/servant-server.cabal
I've already updated Hackage packages via revisions, this PR includes fixes in the repo.
=> Update inter-library version constraints

servant-client-core/src/Servant/Client/Core/HasClient.hs, servant-server/src/Servant/Server/Internal.hs
- Minor fixes of haddock section regarding introduced in #1322 Fragment combinator.
=> Remove extra parameter from haddock section of Fragment instances

servant/src/Servant/Links.hs, servant/test/Servant/LinksSpec.hs
Implements the trivial HasLink UVerb instance and a corresponding test
=> add HasLink instance for UVerb

servant-server/test/Servant/Server/Internal/ContextSpec.hs, stack.yaml
=> Housekeeping

servant-server/servant-server.cabal
Compiles and tests ran without error
=> Bump base64-bytestring limit to 1.3

servant-client-core/servant-client-core.cabal
Builds fine with new base64-bytestring
=> Update upper bound limit of base64-bytestring

servant-client/servant-client.cabal
Builds fine with http-client-0.7.3
=> Update upper bound limit for http-client

README.md, nix/README.md, nix/shell.nix
Improvising the shell.nix file by 
- Pinning nixpkgs
- Adding missing dependencies
and adding documentation about it.
=> pinning nixpkgs and adding missing dependencies to shell.nix file

servant/servant.cabal
=> Allow singleton-bool 0.1.6

servant/servant.cabal
=> Allow attoparsec 0.14

servant-client/servant-client.cabal
=> Allow transformers-compat 0.7

doc/tutorial/ApiType.lhs
=> Document Raw's behaviour when composing APIs

servant-swagger/servant-swagger.cabal, stack.yaml
=> Fix servant-swagger Cabal

.github/workflows/master.yml
Minor updates to GHC and Cabal versions
=> minor updates to GitHub Actions

servant-auth/servant-auth-client/servant-auth-client.cabal, servant-auth/servant-auth-docs/servant-auth-docs.cabal, servant-auth/servant-auth-server/servant-auth-server.cabal, servant-auth/servant-auth-swagger/servant-auth-swagger.cabal, servant-auth/servant-auth/servant-auth.cabal, servant-conduit/servant-conduit.cabal, servant-machines/servant-machines.cabal, servant-pipes/servant-pipes.cabal, servant-swagger/servant-swagger.cabal
some links which appear on Hackage point to non-existing pages. This PR should fix them
=> fix broken links

servant-server/example/greet.hs, servant/src/Servant/API.hs
=> Re-export Servant.API.Generic in Servant.API

servant-docs/src/Servant/Docs/Internal.hs
=> Add support for NamedRoutes in servant-docs

servant-swagger/servant-swagger.cabal
=> Allow hspec 2.10

servant-server/CHANGELOG.md, servant-server/src/Servant/Server/Internal/Router.hs
=> Document `CaptureHint` in `Capture[All]Router`

cabal.project, doc/cookbook/index.rst, doc/cookbook/managed-resource/ManagedResource.lhs, doc/cookbook/managed-resource/managed-resource.cabal, doc/requirements.txt, servant-client-core/src/Servant/Client/Core/HasClient.hs, servant-docs/golden/comprehensive.md, servant-docs/src/Servant/Docs/Internal.hs, servant-foreign/src/Servant/Foreign/Internal.hs, servant-server/src/Servant/Server/Internal.hs, servant-server/test/Servant/ServerSpec.hs, servant-swagger/src/Servant/Swagger/Internal.hs, servant/servant.cabal, servant/src/Servant/API.hs, servant/src/Servant/API/WithResource.hs, servant/src/Servant/Links.hs, servant/src/Servant/Test/ComprehensiveAPI.hs
Hi! This is the PR discussed in #1345 , cookbook included.
=> WithResource combinator for Servant-managed resources

.github/workflows/master.yml
Provisionally disable the Stack CI, it's too flaky.
=> Provisionally disable the Stack CI, it's too flaky.

servant-conduit/servant-conduit.cabal, servant-server/servant-server.cabal
This PR allows for resourcet-1.3 in servant-server and servant-conduit
=> Allow resourcet-1.3 in servant-server and servant-conduit

servant-client-core/servant-client-core.cabal, servant-client/servant-client.cabal, servant-docs/servant-docs.cabal, servant-foreign/servant-foreign.cabal, servant-http-streams/servant-http-streams.cabal, servant-server/servant-server.cabal, servant-swagger/servant-swagger.cabal, servant/servant.cabal
https://github.com/commercialhaskell/stackage/issues/6906
=> Support base-compat 0.13

servant-swagger/README.md
=> Fix link to servant-swagger haddocks

changelog.d/1698, changelog.d/1702, servant-auth/servant-auth-server/src/Servant/Auth/Server/Internal/AddSetCookie.hs
Adding code suggested by @mastarija on issue #1601
=> Add add set cookies instance

cabal.project
Relevant issue seems to be fixed upstream.
=> Fix CI build due to warp / http2 incompatibility

cabal.project
I'll merge myself this if CI passes.
=> Remove unnecessary allow-newers

cabal.project
=> Remove some allow-newers

doc/tutorial/Server.lhs
This corresponds to https://docs.servant.dev/en/stable/tutorial/Authentication.html
=> conclusion of tutorial mentions `servant-auth`

changelog.d/pr-1813, servant/src/Servant/API/Range.hs
A small improvement suggested by @svobot 🙏🏻
=> Derive newtype `ToHttpApiData` in type `Range`

servant-auth/servant-auth-server/CHANGELOG.md, servant-auth/servant-auth-server/servant-auth-server.cabal
=> Prepare servant-auth-server 0.4.9.1

servant-auth/servant-auth-client/servant-auth-client.cabal, servant-auth/servant-auth-docs/servant-auth-docs.cabal, servant-auth/servant-auth-server/servant-auth-server.cabal, servant-auth/servant-auth-swagger/servant-auth-swagger.cabal, servant-client-core/servant-client-core.cabal, servant-client/servant-client.cabal, servant-http-streams/servant-http-streams.cabal, servant-quickcheck/servant-quickcheck.cabal, servant/servant.cabal
=> allow QuickCheck 2.16

cabal.project
All libraries have been updated.
=> Remove allow-newers
